//! The Fq tower and curve-group fixtures, generated against arkworks-bn254.
//!
//! Three files, all written to `crates/curve/tests/vectors/`:
//!
//! * `fq_kats.txt` — Fq and Fq2 arithmetic: an edge grid, 1,000 random
//!   vectors per field, `pow`, and the wire-canonicity cases.
//! * `g1_kats.txt` — G1: the generator's exact bytes, 1,000 random
//!   `(P, Q, k)` vectors, the addition and scalar edge cases, and every
//!   rejection class `from_bytes` has to catch.
//! * `g2_kats.txt` — the same for G2, plus on-curve points outside the
//!   order-`r` subgroup, which G1 cannot have.
//!
//! Every expected value comes from arkworks. Nothing here is `crates/curve`'s
//! own answer read back.
//!
//! # Encoding
//!
//! One token per value, in the wire form `crates/curve` emits: 64 hex
//! characters for an `Fq`, 128 for an `Fq2` (`c0 || c1`), 128 for a G1 point
//! (`x || y`), 256 for a G2 point, each coordinate canonical little-endian.
//! All-zero is the point at infinity. A value that does not exist — the
//! inverse of zero, the root of a nonresidue — is the token `none`, so every
//! line kind has a fixed arity.
//!
//! Point tokens are therefore also a wire-format fixture: the tests parse them
//! coordinate-wise rather than through `from_bytes`, because the off-curve and
//! out-of-subgroup lines are exactly the values `from_bytes` must reject.

use std::fmt::Write as _;

use ark_bn254::{Fq, Fq2, Fr, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::{AffineRepr, CurveGroup, PrimeGroup};
use ark_ff::{AdditiveGroup, BigInteger, Field, One, PrimeField};
use test_support::{to_hex, Rng};

use crate::shared::{hex_exp, hex_fq, hex_fq2, hex_fr, hex_g1, hex_g2, opt_fq, opt_fq2};

const FQ_SEED: u64 = 20260910;
const G1_SEED: u64 = 20260911;
const G2_SEED: u64 = 20260912;

/// Acceptance 1 and 3 both ask for at least a thousand random vectors.
const RANDOM_VECTORS: usize = 1_000;

// ---------------------------------------------------------------------------
// Sampling
// ---------------------------------------------------------------------------

/// Reduced mod q, not rejection-sampled: the vectors want arkworks' own answer
/// for an arbitrary 256-bit input.
fn next_fq(rng: &mut Rng) -> Fq {
    Fq::from_le_bytes_mod_order(&rng.next_le32())
}

fn next_fq2(rng: &mut Rng) -> Fq2 {
    Fq2::new(next_fq(rng), next_fq(rng))
}

fn next_fr(rng: &mut Rng) -> Fr {
    Fr::from_le_bytes_mod_order(&rng.next_le32())
}

/// A uniform point of the order-`r` subgroup: `k * G` for uniform `k`.
fn next_g1(rng: &mut Rng) -> G1Affine {
    (G1Projective::generator() * next_fr(rng)).into_affine()
}

fn next_g2(rng: &mut Rng) -> G2Affine {
    (G2Projective::generator() * next_fr(rng)).into_affine()
}

// ---------------------------------------------------------------------------
// fq_kats.txt
// ---------------------------------------------------------------------------

const FQ_HEADER: &str = "\
# fq_kats v1 -- BN254 base field and Fq2 known-answer tests
# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand
# regenerate: cargo run -p kat-gen
# seed: 20260910 (splitmix64)
#
# One token per value, in wire form: 64 hex characters of canonical
# little-endian Fq, or 128 for an Fq2 written c0 || c1. A value that does not
# exist is the token `none`, so every line kind has a fixed arity.
#
#   fq_ops   <a> <b> <a+b> <a-b> <a*b> <a^2> <1/a> <sqrt a>
#   fq2_ops  <a> <b> <a+b> <a-b> <a*b> <a^2> <1/a> <sqrt a> <conj a> <a*xi>
#   fq_pow   <a> <e> <a^e>          e is a plain 256-bit integer, not reduced
#   fq_bytes <32 bytes> ok|reject   from_bytes accepts iff the value is < q
#   fq_u64   <n> <bytes of n>       from_u64, and the encoding of a small value
#
# `sqrt a` is one of the two roots -- arkworks' choice, which for Fq is
# a^((q+1)/4) and for Fq2 is not the closed form `curve` uses. A test compares
# up to negation and re-squares the root it got.
";

fn fq_ops_line(out: &mut String, a: &Fq, b: &Fq) {
    let _ = writeln!(
        out,
        "fq_ops {} {} {} {} {} {} {} {}",
        hex_fq(a),
        hex_fq(b),
        hex_fq(&(*a + *b)),
        hex_fq(&(*a - *b)),
        hex_fq(&(*a * *b)),
        hex_fq(&a.square()),
        opt_fq(a.inverse()),
        opt_fq(a.sqrt()),
    );
}

fn fq2_ops_line(out: &mut String, a: &Fq2, b: &Fq2, xi: &Fq2) {
    let _ = writeln!(
        out,
        "fq2_ops {} {} {} {} {} {} {} {} {} {}",
        hex_fq2(a),
        hex_fq2(b),
        hex_fq2(&(*a + *b)),
        hex_fq2(&(*a - *b)),
        hex_fq2(&(*a * *b)),
        hex_fq2(&a.square()),
        opt_fq2(a.inverse()),
        opt_fq2(a.sqrt()),
        hex_fq2(&Fq2::new(a.c0, -a.c1)),
        hex_fq2(&(*a * *xi)),
    );
}

fn fq_kats() -> String {
    let mut out = String::from(FQ_HEADER);
    let mut rng = Rng::new(FQ_SEED);

    // R and R^2 as field *values*, as S01's Fr vectors carry them: a wrong
    // Montgomery constant is most visible on its own radix.
    let r: Fq = Fq::from(2u64).pow([256u64, 0, 0, 0]);
    let r2: Fq = r * r;
    let fq_edges: Vec<Fq> = vec![
        Fq::ZERO,
        Fq::one(),
        Fq::from(2u64),
        -Fq::from(2u64), // q - 2
        -Fq::one(),      // q - 1
        r,
        r2,
    ];

    out.push_str("\n# --- Fq on the edge grid: 0, 1, 2, q-2, q-1, R, R^2 ---\n");
    for a in &fq_edges {
        for b in &fq_edges {
            fq_ops_line(&mut out, a, b);
        }
    }

    out.push_str("\n# --- Fq on random pairs ---\n");
    for _ in 0..RANDOM_VECTORS {
        let (a, b) = (next_fq(&mut rng), next_fq(&mut rng));
        fq_ops_line(&mut out, &a, &b);
    }

    // 0, 1, 2, q-2 and 2^256-1 exercise the empty ladder, the identity, one
    // squaring, the Fermat exponent, and an all-ones 256-bit ladder.
    let fixed_exps: [[u64; 4]; 5] = [
        [0, 0, 0, 0],
        [1, 0, 0, 0],
        [2, 0, 0, 0],
        {
            let mut e = Fq::MODULUS.0;
            e[0] -= 2;
            e
        },
        [u64::MAX; 4],
    ];
    out.push_str("\n# --- Fq pow on the edge grid with fixed exponents ---\n");
    for a in &fq_edges {
        for e in &fixed_exps {
            let _ = writeln!(
                out,
                "fq_pow {} {} {}",
                hex_fq(a),
                hex_exp(e),
                hex_fq(&a.pow(e))
            );
        }
    }
    out.push_str("\n# --- Fq pow on random bases and exponents ---\n");
    for _ in 0..40 {
        let a = next_fq(&mut rng);
        let e = rng.next_exp();
        let _ = writeln!(
            out,
            "fq_pow {} {} {}",
            hex_fq(&a),
            hex_exp(&e),
            hex_fq(&a.pow(e))
        );
    }

    // The wire form: what `from_bytes` must take and what it must refuse.
    out.push_str("\n# --- the Fq wire form ---\n");
    let q_bytes = Fq::MODULUS.to_bytes_le();
    let mut cases: Vec<(String, bool)> = vec![
        (to_hex(&[0u8; 32]), true),
        (hex_fq(&Fq::one()), true),
        (hex_fq(&-Fq::one()), true), // q - 1, the largest element
        (to_hex(&q_bytes), false),   // q itself
        (to_hex(&[0xffu8; 32]), false),
    ];
    {
        // q + 1, and the top-bit-set value 2^255, both non-canonical.
        let mut q_plus_one = q_bytes.clone();
        q_plus_one[0] += 1;
        cases.push((to_hex(&q_plus_one), false));
        let mut top = [0u8; 32];
        top[31] = 0x80;
        cases.push((to_hex(&top), false));
    }
    for _ in 0..8 {
        cases.push((hex_fq(&next_fq(&mut rng)), true));
    }
    for (hex, ok) in &cases {
        let _ = writeln!(
            out,
            "fq_bytes {} {}",
            hex,
            if *ok { "ok" } else { "reject" }
        );
    }

    out.push_str("\n# --- from_u64, and the encoding of a small value ---\n");
    for n in [0u64, 1, 2, 3, 9, 255, 256, u32::MAX as u64, u64::MAX] {
        let _ = writeln!(out, "fq_u64 {} {}", n, hex_fq(&Fq::from(n)));
    }

    // xi = 9 + u, the Fq6 nonresidue that `Fq2::mul_by_nonresidue` multiplies
    // by. Taken from arkworks' own tower configuration, not written out here.
    let xi = <ark_bn254::Fq6Config as ark_ff::fields::Fp6Config>::NONRESIDUE;
    assert_eq!(xi, Fq2::new(Fq::from(9u64), Fq::one()), "xi must be 9 + u");

    let fq2_edge_coeffs = [Fq::ZERO, Fq::one(), -Fq::one()];
    let fq2_edges: Vec<Fq2> = fq2_edge_coeffs
        .iter()
        .flat_map(|c0| fq2_edge_coeffs.iter().map(move |c1| Fq2::new(*c0, *c1)))
        .collect();

    out.push_str("\n# --- Fq2 on the edge grid: both coefficients in {0, 1, q-1} ---\n");
    for a in &fq2_edges {
        for b in &fq2_edges {
            fq2_ops_line(&mut out, a, b, &xi);
        }
    }

    out.push_str("\n# --- Fq2 on random pairs ---\n");
    let mut squares = 0usize;
    for _ in 0..RANDOM_VECTORS {
        let (a, b) = (next_fq2(&mut rng), next_fq2(&mut rng));
        if a.sqrt().is_some() {
            squares += 1;
        }
        fq2_ops_line(&mut out, &a, &b, &xi);
    }
    // Roughly half of Fq2 is square. A corpus that landed entirely on one side
    // would test one branch of `sqrt` and look like it tested both.
    assert!(
        (100..=900).contains(&squares),
        "the random Fq2 corpus is lopsided: {squares} squares of {RANDOM_VECTORS}"
    );

    out
}

// ---------------------------------------------------------------------------
// g1_kats.txt and g2_kats.txt
//
// The two are written by separate functions rather than one generic one: the
// coordinate types differ, the rejection classes differ, and two 90-line
// functions read better than one that is parameterized over a curve.
// ---------------------------------------------------------------------------

const G1_HEADER: &str = "\
# g1_kats v1 -- BN254 G1 known-answer tests
# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand
# regenerate: cargo run -p kat-gen
# seed: 20260911 (splitmix64)
#
# A point is 128 hex characters, x || y, each coordinate canonical 32-byte
# little-endian Fq; all-zero is the point at infinity. That is exactly
# G1Affine::to_bytes, so every point token is also a wire-format fixture.
# Scalars are 32 bytes of canonical little-endian Fr.
#
#   g1_generator   <P>                             GENERATOR's exact bytes
#   g1_ops         <P> <Q> <k> <P+Q> <2P> <kP> <-P>
#   g1_add_edge    <name> <P> <Q> <P+Q>            infinity and P +- P
#   g1_madd_edge   <P> <2P> <4P> <-2P>             mixed add against Z != 1
#   g1_scalar_edge <name> <P> <k> <kP>             k = 0, 1, r-1, r
#   g1_reject      <P> <reason>                    from_bytes must return None
#
# Rejection reasons name the class from S05's Must-be-exact 3: non_canonical_x,
# non_canonical_y, off_curve, and nonzero_infinity_pattern (an encoding that is
# all-zero but for one byte, so it is not infinity and is not on the curve).
#
# The `k = r` scalar edge is the one line whose scalar is not an Fr value: r is
# Fr's modulus, so `Fr::from_bytes` rejects it. See the test.
";

const G2_HEADER: &str = "\
# g2_kats v1 -- BN254 G2 known-answer tests
# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand
# regenerate: cargo run -p kat-gen
# seed: 20260912 (splitmix64)
#
# A point is 256 hex characters, x.c0 || x.c1 || y.c0 || y.c1, each 32-byte
# canonical little-endian Fq; all-zero is the point at infinity. Line kinds
# mirror g1_kats.txt exactly, with one extra rejection reason: G2's cofactor is
# 2q - r, so an on-curve point need not be in the order-r subgroup, and the
# `not_in_subgroup` lines are on-curve points that are not.
";

/// A serialized point, its expected `is_on_curve`, and why `from_bytes`
/// rejects it. `on_curve` is what separates a real point with a mangled
/// coordinate from one that never was on the curve.
struct Rejection {
    hex: String,
    reason: &'static str,
}

fn g1_kats() -> String {
    let mut out = String::from(G1_HEADER);
    let mut rng = Rng::new(G1_SEED);
    let generator = G1Affine::generator();

    out.push_str("\n# --- the generator's wire bytes ---\n");
    let _ = writeln!(out, "g1_generator {}", hex_g1(&generator));

    out.push_str("\n# --- random (P, Q, k) ---\n");
    let mut seen: Vec<String> = Vec::new();
    for _ in 0..RANDOM_VECTORS {
        let (p, q, k) = (next_g1(&mut rng), next_g1(&mut rng), next_fr(&mut rng));
        let sum = (p + q).into_affine();
        let dbl = p.into_group().double().into_affine();
        let scaled = (p.into_group() * k).into_affine();
        assert!(!p.is_zero() && !q.is_zero(), "a random point must not be O");
        seen.push(hex_g1(&p));
        let _ = writeln!(
            out,
            "g1_ops {} {} {} {} {} {} {}",
            hex_g1(&p),
            hex_g1(&q),
            hex_fr(&k),
            hex_g1(&sum),
            hex_g1(&dbl),
            hex_g1(&scaled),
            hex_g1(&-p),
        );
    }
    crate::assert_distinct(&seen, "G1 random points");

    // The addition edges. `P + P` here goes through the *generic* add path in
    // the test, which is the case the H == 0, r == 0 branch exists for.
    let p = next_g1(&mut rng);
    let inf = G1Affine::identity();
    out.push_str("\n# --- addition edges ---\n");
    for (name, a, b) in [
        ("p_plus_inf", p, inf),
        ("inf_plus_p", inf, p),
        ("inf_plus_inf", inf, inf),
        ("p_plus_p", p, p),
        ("p_plus_neg_p", p, -p),
        ("gen_plus_neg_gen", generator, -generator),
    ] {
        let _ = writeln!(
            out,
            "g1_add_edge {} {} {} {}",
            name,
            hex_g1(&a),
            hex_g1(&b),
            hex_g1(&(a + b).into_affine()),
        );
    }

    // Mixed addition where the affine operand equals, and negates, a
    // projective operand whose Z is not 1. The test builds `2P` by doubling,
    // so its Z is `2 y`, and then adds `2P` and `-2P` to it.
    out.push_str("\n# --- mixed-add edges against a Z != 1 accumulator ---\n");
    let two_p = p.into_group().double();
    let _ = writeln!(
        out,
        "g1_madd_edge {} {} {} {}",
        hex_g1(&p),
        hex_g1(&two_p.into_affine()),
        hex_g1(&two_p.double().into_affine()),
        hex_g1(&(-two_p).into_affine()),
    );

    out.push_str("\n# --- scalar edges ---\n");
    let r_bytes = to_hex(&Fr::MODULUS.to_bytes_le());
    let scalar_edges: Vec<(&str, String, G1Affine)> = vec![
        ("k_zero", hex_fr(&Fr::ZERO), G1Affine::identity()),
        ("k_one", hex_fr(&Fr::one()), p),
        ("k_r_minus_one", hex_fr(&-Fr::one()), -p),
        ("k_r", r_bytes, G1Affine::identity()),
    ];
    for (name, k, expected) in &scalar_edges {
        let _ = writeln!(
            out,
            "g1_scalar_edge {} {} {} {}",
            name,
            hex_g1(&p),
            k,
            hex_g1(expected),
        );
    }

    out.push_str("\n# --- from_bytes rejection classes ---\n");
    for rejection in g1_rejections(&mut rng) {
        let _ = writeln!(out, "g1_reject {} {}", rejection.hex, rejection.reason);
    }

    out
}

fn g1_rejections(rng: &mut Rng) -> Vec<Rejection> {
    let q_hex = to_hex(&Fq::MODULUS.to_bytes_le());
    let ones_hex = to_hex(&[0xffu8; 32]);
    let mut out = Vec::new();

    for _ in 0..4 {
        let p = next_g1(rng);
        // y + 1: the curve equation has at most two roots for a given x, and
        // y and -y are both of them, so y + 1 is off the curve unless
        // y + 1 == -y. Asserted, not assumed.
        let bad_y = p.y + Fq::one();
        assert_ne!(bad_y, -p.y);
        assert!(
            !G1Affine::new_unchecked(p.x, bad_y).is_on_curve(),
            "y + 1 must leave the curve"
        );
        out.push(Rejection {
            hex: format!("{}{}", hex_fq(&p.x), hex_fq(&bad_y)),
            reason: "off_curve",
        });
    }

    // Must-be-exact 3's fourth class: an encoding that is all-zero except for
    // one byte is *not* infinity, and every such coordinate pair is off the
    // curve. `x = 0` has no on-curve `y` at all, because 3 is a nonresidue mod
    // q and `y^2 = 3` has no solution -- which is also what makes the all-zero
    // infinity encoding unambiguous. Asserted here, not assumed.
    assert!(
        Fq::from(3u64).sqrt().is_none(),
        "3 must be a nonresidue mod q"
    );
    let zeros = to_hex(&[0u8; 32]);
    for hex in [
        format!("{}{}", zeros, hex_fq(&Fq::one())),
        format!("{}{}", hex_fq(&Fq::one()), zeros),
    ] {
        out.push(Rejection {
            hex,
            reason: "nonzero_infinity_pattern",
        });
    }

    let p = next_g1(rng);
    out.push(Rejection {
        hex: format!("{}{}", q_hex, hex_fq(&p.y)),
        reason: "non_canonical_x",
    });
    out.push(Rejection {
        hex: format!("{}{}", hex_fq(&p.x), q_hex),
        reason: "non_canonical_y",
    });
    out.push(Rejection {
        hex: format!("{}{}", ones_hex, hex_fq(&p.y)),
        reason: "non_canonical_x",
    });
    out.push(Rejection {
        hex: format!("{}{}", hex_fq(&p.x), ones_hex),
        reason: "non_canonical_y",
    });
    out
}

fn g2_kats() -> String {
    let mut out = String::from(G2_HEADER);
    let mut rng = Rng::new(G2_SEED);
    let generator = G2Affine::generator();

    out.push_str("\n# --- the generator's wire bytes ---\n");
    let _ = writeln!(out, "g2_generator {}", hex_g2(&generator));

    out.push_str("\n# --- random (P, Q, k) ---\n");
    let mut seen: Vec<String> = Vec::new();
    for _ in 0..RANDOM_VECTORS {
        let (p, q, k) = (next_g2(&mut rng), next_g2(&mut rng), next_fr(&mut rng));
        let sum = (p + q).into_affine();
        let dbl = p.into_group().double().into_affine();
        let scaled = (p.into_group() * k).into_affine();
        assert!(!p.is_zero() && !q.is_zero(), "a random point must not be O");
        seen.push(hex_g2(&p));
        let _ = writeln!(
            out,
            "g2_ops {} {} {} {} {} {} {}",
            hex_g2(&p),
            hex_g2(&q),
            hex_fr(&k),
            hex_g2(&sum),
            hex_g2(&dbl),
            hex_g2(&scaled),
            hex_g2(&-p),
        );
    }
    crate::assert_distinct(&seen, "G2 random points");

    let p = next_g2(&mut rng);
    let inf = G2Affine::identity();
    out.push_str("\n# --- addition edges ---\n");
    for (name, a, b) in [
        ("p_plus_inf", p, inf),
        ("inf_plus_p", inf, p),
        ("inf_plus_inf", inf, inf),
        ("p_plus_p", p, p),
        ("p_plus_neg_p", p, -p),
        ("gen_plus_neg_gen", generator, -generator),
    ] {
        let _ = writeln!(
            out,
            "g2_add_edge {} {} {} {}",
            name,
            hex_g2(&a),
            hex_g2(&b),
            hex_g2(&(a + b).into_affine()),
        );
    }

    out.push_str("\n# --- mixed-add edges against a Z != 1 accumulator ---\n");
    let two_p = p.into_group().double();
    let _ = writeln!(
        out,
        "g2_madd_edge {} {} {} {}",
        hex_g2(&p),
        hex_g2(&two_p.into_affine()),
        hex_g2(&two_p.double().into_affine()),
        hex_g2(&(-two_p).into_affine()),
    );

    out.push_str("\n# --- scalar edges ---\n");
    let r_bytes = to_hex(&Fr::MODULUS.to_bytes_le());
    for (name, k, expected) in [
        ("k_zero", hex_fr(&Fr::ZERO), G2Affine::identity()),
        ("k_one", hex_fr(&Fr::one()), p),
        ("k_r_minus_one", hex_fr(&-Fr::one()), -p),
        ("k_r", r_bytes, G2Affine::identity()),
    ] {
        let _ = writeln!(
            out,
            "g2_scalar_edge {} {} {} {}",
            name,
            hex_g2(&p),
            k,
            hex_g2(&expected),
        );
    }

    out.push_str("\n# --- from_bytes rejection classes ---\n");
    for rejection in g2_rejections(&mut rng) {
        let _ = writeln!(out, "g2_reject {} {}", rejection.hex, rejection.reason);
    }

    out
}

fn g2_rejections(rng: &mut Rng) -> Vec<Rejection> {
    let q_hex = to_hex(&Fq::MODULUS.to_bytes_le());
    let mut out = Vec::new();

    // On-curve, outside the order-r subgroup: a random x with the cofactor
    // left un-cleared. G1 cannot have these -- its cofactor is 1 -- which is
    // why acceptance 5's G1 half uses off-curve points instead.
    let b2 = <ark_bn254::g2::Config as ark_ec::short_weierstrass::SWCurveConfig>::COEFF_B;
    let mut found = 0;
    while found < 4 {
        let x = next_fq2(rng);
        let Some(y) = (x * x * x + b2).sqrt() else {
            continue;
        };
        let point = G2Affine::new_unchecked(x, y);
        assert!(point.is_on_curve(), "constructed from the curve equation");
        assert!(
            !point.is_in_correct_subgroup_assuming_on_curve(),
            "an un-cleared random point is almost never in the subgroup"
        );
        out.push(Rejection {
            hex: hex_g2(&point),
            reason: "not_in_subgroup",
        });
        found += 1;
    }

    // Must-be-exact 3's fourth class, once per coordinate half.
    let zeros = to_hex(&[0u8; 32]);
    let one = hex_fq(&Fq::one());
    for half in 0..4 {
        let hex: String = (0..4)
            .map(|i| {
                if i == half {
                    one.as_str()
                } else {
                    zeros.as_str()
                }
            })
            .collect();
        out.push(Rejection {
            hex,
            reason: "nonzero_infinity_pattern",
        });
    }

    for _ in 0..2 {
        let p = next_g2(rng);
        let bad_y = p.y + Fq2::one();
        assert_ne!(bad_y, -p.y);
        assert!(
            !G2Affine::new_unchecked(p.x, bad_y).is_on_curve(),
            "y + 1 must leave the curve"
        );
        out.push(Rejection {
            hex: format!("{}{}", hex_fq2(&p.x), hex_fq2(&bad_y)),
            reason: "off_curve",
        });
    }

    let p = next_g2(rng);
    out.push(Rejection {
        hex: format!("{}{}{}", q_hex, zeros, hex_fq2(&p.y)),
        reason: "non_canonical_x",
    });
    out.push(Rejection {
        hex: format!("{}{}{}", zeros, q_hex, hex_fq2(&p.y)),
        reason: "non_canonical_x",
    });
    out.push(Rejection {
        hex: format!("{}{}{}", hex_fq2(&p.x), q_hex, zeros),
        reason: "non_canonical_y",
    });
    out.push(Rejection {
        hex: format!("{}{}{}", hex_fq2(&p.x), zeros, q_hex),
        reason: "non_canonical_y",
    });
    out
}

// ---------------------------------------------------------------------------

pub fn generate() {
    for (name, contents) in [
        ("fq_kats.txt", fq_kats()),
        ("g1_kats.txt", g1_kats()),
        ("g2_kats.txt", g2_kats()),
    ] {
        crate::write_vectors(&format!("crates/curve/tests/vectors/{name}"), &contents);
    }
}
