//! `crates/loader`'s fixtures: the derived listings, the synthetic ELFs and
//! the fib public-I/O record.
//!
//! Everything here is a deterministic function of files already in the tree —
//! the committed guest ELFs — or of nothing at all. That is what lets CI
//! regenerate it and diff. The guest ELFs themselves are *not* regenerated
//! here; see `guests.rs` for why.
//!
//! The listings come from `llvm-objdump` and `llvm-nm` out of the pinned
//! toolchain's `llvm-tools` component, so the disassembler is pinned exactly as
//! the compiler is.

use std::path::PathBuf;
use std::process::Command;

use crate::write_vectors;

/// The guest ELFs the loader tests read, and what each is for.
pub const ELF_FIXTURES: [(&str, &str); 7] = [
    (
        "fib",
        "real compiler output: the address and boundary oracle",
    ),
    ("echo", "the ecall shims under QEMU"),
    ("rvc-dense", "the paired regions: the expansion oracle"),
    (
        "amm",
        "open-coded 128- and 256-bit arithmetic, and the c.unimp padding an \
         exhaustive dispatch emits",
    ),
    (
        "orderbook",
        "the heap, the collections, and the hint-then-verify pattern",
    ),
    (
        "vault",
        "field and transcript inside the proof: Poseidon2, Fr::inverse, deep \
         recursion",
    ),
    (
        "atomics",
        "every A-extension instruction as the compiler emits them: the atomics \
         family's fixture, and the one S11 force-detaches",
    ),
];

/// The ones the objdump differential runs against.
///
/// Not `echo`: its listing is 300 kB of the same kind of evidence `fib`
/// already gives, and its job here is to run under QEMU. `amm` earns one where
/// the other two new guests do not, for two reasons. Its text is long stretches
/// of open-coded 128-bit arithmetic -- LLVM legalises `i128` into 32-bit limbs
/// on this target and calls no builtin for it, so the multiply, the shifts and
/// the compares are all written out in line, which is a shape no hand-written
/// fixture would produce. And it carries the `c.unimp` padding whose carve-out
/// `differential.rs` now has to get right, in the smallest quantity of the
/// three: exactly one halfword, against `vault`'s two and `orderbook`'s
/// sixteen.
const DISASSEMBLED: [&str; 3] = ["fib", "rvc-dense", "amm"];

pub fn generate() {
    for name in DISASSEMBLED {
        objdump_listing(name);
    }
    nm_listing("rvc-dense");
    synthetic_elfs();
    fib_io();
}

// ---------------------------------------------------------------------------
// Derived listings
// ---------------------------------------------------------------------------

/// `<name>.objdump.txt`: one line per instruction, `address encoding text`.
///
/// The test compares the **address and the encoding**, not the text. The text
/// is there so a human can read the diff — it is `-M no-aliases`, so `ret` and
/// `mv` appear as the instructions they are.
fn objdump_listing(name: &str) {
    let elf = vector_path(&format!("{name}.elf"));
    let out = run(
        llvm_tool("llvm-objdump"),
        &[
            "--disassemble",
            "--no-print-imm-hex",
            "-M",
            "no-aliases",
            elf.to_str().expect("fixture paths are UTF-8"),
        ],
    );

    let mut body = String::new();
    let mut count = 0usize;
    for line in out.lines() {
        let Some((addr, enc, text)) = parse_objdump_line(line) else {
            continue;
        };
        body.push_str(&format!("{addr:08x} {enc} {text}\n"));
        count += 1;
    }
    assert!(
        count > 16,
        "{name}: objdump listed only {count} instructions"
    );

    write_vectors(
        &format!("crates/loader/tests/vectors/{name}.objdump.txt"),
        &format!(
            "# `llvm-objdump -d -M no-aliases` of {name}.elf, one line per instruction.\n\
             # Generated by `cargo run -p kat-gen -- loader`. Do not edit.\n\
             #\n\
             # Fields: address, raw encoding as it sits in the file, disassembly.\n\
             # The differential test compares the first two against the loader's\n\
             # ProgramImage at every address; the third is for the reader.\n\
             #\n\
             # {count} instructions.\n\
             {body}"
        ),
    );
}

/// Split one `llvm-objdump -d` body line into `(address, encoding, text)`.
///
/// Returns `None` for the file banner, the section banner, symbol headers and
/// blank lines — everything that is not an instruction.
pub(crate) fn parse_objdump_line(line: &str) -> Option<(u32, String, String)> {
    // An instruction line starts with whitespace, then `address:`.
    if !line.starts_with(char::is_whitespace) {
        return None;
    }
    let (addr, rest) = line.split_once(':')?;
    let addr = u32::from_str_radix(addr.trim(), 16).ok()?;

    let mut fields = rest.split_whitespace();
    let encoding = fields.next()?.to_string();
    // The raw encoding is 4 or 8 hex digits; anything else is not an
    // instruction line we understand, and silently skipping one would make the
    // differential weaker without saying so.
    assert!(
        (encoding.len() == 4 || encoding.len() == 8)
            && encoding.chars().all(|c| c.is_ascii_hexdigit()),
        "unexpected objdump line: {line}"
    );
    let text = fields.collect::<Vec<_>>().join(" ");
    Some((addr, encoding, text))
}

/// `<name>.nm.txt`: the text symbols, `address name`, sorted.
///
/// Acceptance 5 is about these: every symbol address must be the address of an
/// instruction in the image, which is what "addresses are never compacted"
/// means in practice.
fn nm_listing(name: &str) {
    let elf = vector_path(&format!("{name}.elf"));
    let out = run(
        llvm_tool("llvm-nm"),
        &[elf.to_str().expect("fixture paths are UTF-8")],
    );

    let mut rows: Vec<(u32, String)> = Vec::new();
    for line in out.lines() {
        let mut fields = line.split_whitespace();
        let (Some(addr), Some(kind), Some(symbol)) = (fields.next(), fields.next(), fields.next())
        else {
            continue;
        };
        // `t`/`T` is the text section. Absolute and data symbols are not
        // instruction addresses and would make the check meaningless.
        if kind != "t" && kind != "T" {
            continue;
        }
        let Ok(addr) = u32::from_str_radix(addr, 16) else {
            continue;
        };
        rows.push((addr, symbol.to_string()));
    }
    rows.sort();
    rows.dedup();
    assert!(
        rows.len() > 4,
        "{name}: nm listed only {} symbols",
        rows.len()
    );

    let body: String = rows
        .iter()
        .map(|(addr, symbol)| format!("{addr:08x} {symbol}\n"))
        .collect();
    write_vectors(
        &format!("crates/loader/tests/vectors/{name}.nm.txt"),
        &format!(
            "# `llvm-nm` of {name}.elf, text symbols only, sorted.\n\
             # Generated by `cargo run -p kat-gen -- loader`. Do not edit.\n\
             #\n\
             # Fields: address, symbol. Every one of these addresses must be the\n\
             # address of an instruction in the ProgramImage.\n\
             #\n\
             # {} symbols.\n\
             {body}",
            rows.len()
        ),
    );
}

// ---------------------------------------------------------------------------
// Synthetic ELFs
// ---------------------------------------------------------------------------

/// A hand-built ELF: 52-byte header, program headers, then the segment bodies.
///
/// Small enough to read, which is the point — every negative control is a
/// named deviation from this one shape, and no toolchain will produce most of
/// them for RV32.
pub(crate) struct ElfBuilder {
    pub(crate) e_type: u16,
    e_machine: u16,
    ei_class: u8,
    entry: u32,
    /// `(p_type, p_flags, vaddr, filesz_bytes, memsz)`.
    segments: Vec<(u32, u32, u32, Vec<u8>, u32)>,
}

impl ElfBuilder {
    /// A minimal, valid, static RV32 executable with one `R|X` segment.
    pub(crate) fn rv32_exec(text: &[u8]) -> ElfBuilder {
        ElfBuilder {
            e_type: 2,
            e_machine: 243,
            ei_class: 1,
            entry: 0x0001_0000,
            segments: vec![(1, 5, 0x0001_0000, text.to_vec(), text.len() as u32)],
        }
    }

    pub(crate) fn build(&self) -> Vec<u8> {
        const EHDR: usize = 52;
        const PHDR: usize = 32;
        let body_at = EHDR + PHDR * self.segments.len();

        let mut out = Vec::new();
        out.extend_from_slice(&[0x7f, b'E', b'L', b'F', self.ei_class, 1, 1, 0]);
        out.extend_from_slice(&[0u8; 8]);
        out.extend_from_slice(&self.e_type.to_le_bytes());
        out.extend_from_slice(&self.e_machine.to_le_bytes());
        out.extend_from_slice(&1u32.to_le_bytes()); // e_version
        out.extend_from_slice(&self.entry.to_le_bytes());
        out.extend_from_slice(&(EHDR as u32).to_le_bytes()); // e_phoff
        out.extend_from_slice(&0u32.to_le_bytes()); // e_shoff
        out.extend_from_slice(&1u32.to_le_bytes()); // e_flags: EF_RISCV_RVC
        out.extend_from_slice(&(EHDR as u16).to_le_bytes());
        out.extend_from_slice(&(PHDR as u16).to_le_bytes());
        out.extend_from_slice(&(self.segments.len() as u16).to_le_bytes());
        out.extend_from_slice(&40u16.to_le_bytes()); // e_shentsize
        out.extend_from_slice(&0u16.to_le_bytes()); // e_shnum
        out.extend_from_slice(&0u16.to_le_bytes()); // e_shstrndx
        assert_eq!(out.len(), EHDR);

        let mut offset = body_at;
        for (p_type, p_flags, vaddr, bytes, memsz) in &self.segments {
            out.extend_from_slice(&p_type.to_le_bytes());
            out.extend_from_slice(&(offset as u32).to_le_bytes());
            out.extend_from_slice(&vaddr.to_le_bytes());
            out.extend_from_slice(&vaddr.to_le_bytes()); // p_paddr
            out.extend_from_slice(&(bytes.len() as u32).to_le_bytes());
            out.extend_from_slice(&memsz.to_le_bytes());
            out.extend_from_slice(&p_flags.to_le_bytes());
            out.extend_from_slice(&4u32.to_le_bytes()); // p_align
            offset += bytes.len();
        }
        assert_eq!(out.len(), body_at);

        for (_, _, _, bytes, _) in &self.segments {
            out.extend_from_slice(bytes);
        }
        out
    }
}

/// `c.nop`, then `c.jr ra`: two halfwords that decode, so a fixture's failure
/// is always the thing it is named after.
const GOOD_TEXT: [u8; 4] = [0x01, 0x00, 0x82, 0x80];

fn synthetic_elfs() {
    // Each entry: file name, why it exists, the bytes.
    let mut cases: Vec<(&str, &str, Vec<u8>)> = vec![(
        "minimal",
        "a valid one-segment RV32 executable: the positive control for every \
         negative below, and proof that the builder itself is right",
        ElfBuilder::rv32_exec(&GOOD_TEXT).build(),
    )];

    // -- the RVC negatives -------------------------------------------------
    cases.push((
        "zero_halfword",
        "an all-zero halfword after a c.nop: RVC's defined-illegal encoding, \
         which the sweep records as not code rather than refusing -- this one \
         is a positive fixture, not a negative",
        ElfBuilder::rv32_exec(&[0x01, 0x00, 0x00, 0x00]).build(),
    ));
    cases.push((
        "zero_halfword_run",
        "c.nop, two all-zero halfwords, c.jr ra, one more, c.nop: the sweep \
         must resynchronise on the far side of padding rather than swallow \
         what follows it. The lone halfword is the load-bearing one -- after a \
         pair, a sweep that over-advanced by two bytes would land on the \
         second and look correct, because an unswept slot is already \
         NonInstruction",
        ElfBuilder::rv32_exec(&[
            0x01, 0x00, // c.nop
            0x00, 0x00, // padding
            0x00, 0x00, // padding
            0x82, 0x80, // c.jr ra
            0x00, 0x00, // padding, alone this time
            0x01, 0x00, // c.nop -- only a correctly resynchronised sweep finds it
        ])
        .build(),
    ));
    cases.push((
        "reserved_addi4spn",
        "c.addi4spn a0, sp, 0 (0x0008): nzuimm = 0 is reserved",
        ElfBuilder::rv32_exec(&[0x01, 0x00, 0x08, 0x00]).build(),
    ));
    cases.push((
        "zcmp",
        "0xb872, a cm.push-shaped halfword in quadrant 2 funct3 = 101: the Zcmp \
         encoding space, which RV32IMAC does not have",
        ElfBuilder::rv32_exec(&[0x01, 0x00, 0x72, 0xb8]).build(),
    ));
    cases.push((
        "instruction_too_long",
        "0x0000_001f: bits 4:2 all ones, so a 48-bit encoding",
        ElfBuilder::rv32_exec(&[0x1f, 0x00, 0x00, 0x00]).build(),
    ));
    cases.push((
        "text_truncated",
        "a 32-bit instruction whose second halfword is past the end of the \
         segment",
        ElfBuilder::rv32_exec(&[0x01, 0x00, 0x13, 0x00]).build(),
    ));

    // -- the ELF negatives -------------------------------------------------
    let mut dyn_type = ElfBuilder::rv32_exec(&GOOD_TEXT);
    dyn_type.e_type = 3;
    cases.push((
        "et_dyn",
        "e_type = ET_DYN: a shared object or PIE, which needs a dynamic linker",
        dyn_type.build(),
    ));

    let mut pt_dynamic = ElfBuilder::rv32_exec(&GOOD_TEXT);
    pt_dynamic
        .segments
        .push((2, 6, 0x0002_0000, vec![0u8; 8], 8));
    cases.push((
        "pt_dynamic",
        "a static-looking executable carrying a PT_DYNAMIC segment",
        pt_dynamic.build(),
    ));

    let mut rel = ElfBuilder::rv32_exec(&GOOD_TEXT);
    rel.e_type = 1;
    cases.push((
        "et_rel",
        "e_type = ET_REL: a relocatable object, which is not a program",
        rel.build(),
    ));

    let mut arm = ElfBuilder::rv32_exec(&GOOD_TEXT);
    arm.e_machine = 40;
    cases.push(("not_riscv", "e_machine = EM_ARM", arm.build()));

    let mut elf64 = ElfBuilder::rv32_exec(&GOOD_TEXT);
    elf64.ei_class = 2;
    cases.push((
        "elf64",
        "EI_CLASS = ELFCLASS64: the header would not even parse as 32-bit",
        elf64.build(),
    ));

    let mut no_exec = ElfBuilder::rv32_exec(&GOOD_TEXT);
    no_exec.segments[0].1 = 4; // PF_R only
    cases.push((
        "no_executable_segment",
        "one PT_LOAD, read-only: an image with no instruction stream",
        no_exec.build(),
    ));

    let mut overlap = ElfBuilder::rv32_exec(&GOOD_TEXT);
    overlap.segments.push((1, 4, 0x0001_0002, vec![0u8; 4], 4));
    cases.push((
        "overlapping_segments",
        "two PT_LOADs whose memory spans intersect",
        overlap.build(),
    ));

    let mut entry_mid = ElfBuilder::rv32_exec(&[0x13, 0x00, 0x00, 0x00]); // one 32-bit nop
    entry_mid.entry = 0x0001_0002;
    cases.push((
        "entry_mid_instruction",
        "e_entry pointing at the second halfword of a 32-bit instruction",
        entry_mid.build(),
    ));

    let mut index = String::from(
        "# Synthetic ELF fixtures for crates/loader.\n\
         # Generated by `cargo run -p kat-gen -- loader`. Do not edit.\n\
         #\n\
         # Hand-built rather than compiled: no RV32 toolchain will emit most of\n\
         # these, and a fixture that is 100 bytes long is one a reviewer can read\n\
         # in full. `minimal.elf` is the shape they all deviate from.\n\
         #\n\
         # Fields: file name, sha256 of the file, what it is.\n",
    );
    let mut rows: Vec<(String, String, String)> = Vec::new();
    for (name, why, bytes) in cases {
        let path = format!("crates/loader/tests/vectors/{name}.elf");
        crate::write_bytes(&path, &bytes);
        rows.push((
            format!("{name}.elf"),
            test_support::to_hex(&test_support::sha256(&bytes)),
            why.split_whitespace().collect::<Vec<_>>().join(" "),
        ));
    }
    rows.sort();
    for (name, digest, why) in rows {
        index.push_str(&format!("{name} {digest} {why}\n"));
    }
    write_vectors("crates/loader/tests/vectors/synthetic_elfs.txt", &index);
}

// ---------------------------------------------------------------------------
// The fib public-I/O record
// ---------------------------------------------------------------------------

/// The two byte streams `guests/fib` is expected to produce, host-computed.
///
/// The QEMU test asserts the guest agrees; the digest test hashes them. Both
/// streams are little-endian `u32`, which is the whole of fib's I/O contract.
fn fib_io() {
    const N: u32 = 24;
    let mut a: u32 = 0;
    let mut b: u32 = 1;
    for _ in 0..N {
        let next = a.wrapping_add(b);
        a = b;
        b = next;
    }
    let input = N.to_le_bytes();
    let output = a.to_le_bytes();
    write_vectors(
        "crates/loader/tests/vectors/fib_io.txt",
        &format!(
            "# guests/fib's public I/O: fd 0 in, fd 1 out.\n\
             # Generated by `cargo run -p kat-gen -- loader`. Do not edit.\n\
             #\n\
             # fib({N}) = {a}, both streams a little-endian u32. The QEMU test\n\
             # checks the guest produces this; the digest test hashes it.\n\
             n {N}\n\
             value {a}\n\
             input {}\n\
             output {}\n",
            test_support::to_hex(&input),
            test_support::to_hex(&output),
        ),
    );
}

// ---------------------------------------------------------------------------
// Toolchain plumbing
// ---------------------------------------------------------------------------

/// Absolute path to a tool from the pinned toolchain's `llvm-tools` component.
///
/// Not `PATH`: the disassembler has to be the one that matches the compiler,
/// and `rust-toolchain.toml` is what pins it.
pub fn llvm_tool(name: &str) -> PathBuf {
    let sysroot = run("rustc", &["--print", "sysroot"]);
    let version = run("rustc", &["-vV"]);
    let host = version
        .lines()
        .find_map(|l| l.strip_prefix("host: "))
        .expect("`rustc -vV` always reports a host triple")
        .trim();
    let path = PathBuf::from(sysroot.trim())
        .join("lib/rustlib")
        .join(host)
        .join("bin")
        .join(name);
    assert!(
        path.exists(),
        "{} is missing: run `rustup component add llvm-tools`. \
         It is in rust-toolchain.toml, so this should not happen.",
        path.display()
    );
    path
}

pub fn vector_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../crates/loader/tests/vectors")
        .join(name)
}

/// Run a command and return its stdout, or die saying which one failed.
pub fn run<S: AsRef<std::ffi::OsStr>>(program: S, args: &[&str]) -> String {
    let program = program.as_ref();
    let out = Command::new(program)
        .args(args)
        .output()
        .unwrap_or_else(|e| panic!("running {}: {e}", program.to_string_lossy()));
    assert!(
        out.status.success(),
        "{} {:?} failed: {}",
        program.to_string_lossy(),
        args,
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).expect("tool output is UTF-8")
}
