//! Regenerates the committed `Fr` known-answer-test vectors from arkworks.
//!
//!     cargo run -p kat-gen
//!
//! Deterministic: same toolchain and same arkworks version produce byte-identical
//! output, so a refresh is `cargo run -p kat-gen && git diff`. Freshness is a
//! manual step; CI only reads the committed file.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use ark_bn254::Fr;
use ark_ff::{AdditiveGroup, BigInteger, Field, One, PrimeField, Zero};

const SEED: u64 = 20260903;
const RANDOM_BINARY: usize = 60;
const RANDOM_UNARY: usize = 60;
const RANDOM_POW: usize = 40;

/// splitmix64. Owned here so the fixture does not depend on any RNG crate's
/// stream staying stable across versions.
struct Rng(u64);

impl Rng {
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    fn next_exp(&mut self) -> [u64; 4] {
        [
            self.next_u64(),
            self.next_u64(),
            self.next_u64(),
            self.next_u64(),
        ]
    }

    fn next_fr(&mut self) -> Fr {
        let mut bytes = [0u8; 32];
        for i in 0..4 {
            bytes[8 * i..8 * i + 8].copy_from_slice(&self.next_u64().to_le_bytes());
        }
        Fr::from_le_bytes_mod_order(&bytes)
    }
}

fn hex_fr(x: &Fr) -> String {
    let bytes = x.into_bigint().to_bytes_le();
    assert_eq!(bytes.len(), 32, "Fr must serialize to 32 bytes");
    hex(&bytes)
}

fn hex_exp(e: &[u64; 4]) -> String {
    let mut bytes = [0u8; 32];
    for i in 0..4 {
        bytes[8 * i..8 * i + 8].copy_from_slice(&e[i].to_le_bytes());
    }
    hex(&bytes)
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(2 * bytes.len());
    for b in bytes {
        write!(s, "{:02x}", b).expect("writing to a String cannot fail");
    }
    s
}

fn main() {
    let mut rng = Rng(SEED);
    let mut out = String::new();

    out.push_str("# fr_kats v1 -- BN254 scalar field known-answer tests\n");
    out.push_str("# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand\n");
    out.push_str("# regenerate: cargo run -p kat-gen\n");
    out.push_str("# seed: 20260903 (splitmix64)\n");
    out.push_str("#\n");
    out.push_str("# Field elements and exponents are 32 bytes of lowercase hex in\n");
    out.push_str("# little-endian byte order, exactly as Fr::to_bytes emits them.\n");
    out.push_str("# Exponents are plain 256-bit integers and are not reduced mod p.\n");
    out.push_str("#\n");
    out.push_str("#   add|sub|mul <a> <b> <c>   c = a op b\n");
    out.push_str("#   square      <a> <c>       c = a * a\n");
    out.push_str("#   inv         <a> <c>       c = a^-1, or the literal `none` for a = 0\n");
    out.push_str("#   pow         <a> <e> <c>   c = a^e\n");

    // 2^256 mod p and its square, as field element *values*: acceptance 3 asks
    // for R and R^2 as inputs to every operator.
    let r: Fr = Fr::from(2u64).pow([256u64, 0, 0, 0]);
    let r2: Fr = r * r;
    let edges: Vec<Fr> = vec![
        Fr::ZERO,
        Fr::one(),
        Fr::from(2u64),
        -Fr::from(2u64), // p - 2
        -Fr::one(),      // p - 1
        r,
        r2,
    ];

    out.push_str("\n# --- binary ops on the edge set: 0, 1, 2, p-2, p-1, R, R^2 ---\n");
    for a in &edges {
        for b in &edges {
            binary(&mut out, a, b);
        }
    }

    out.push_str("\n# --- binary ops on random pairs ---\n");
    for _ in 0..RANDOM_BINARY {
        let a = rng.next_fr();
        let b = rng.next_fr();
        binary(&mut out, &a, &b);
    }

    out.push_str("\n# --- unary ops on the edge set ---\n");
    for a in &edges {
        unary(&mut out, a);
    }

    out.push_str("\n# --- unary ops on random inputs ---\n");
    for _ in 0..RANDOM_UNARY {
        let a = rng.next_fr();
        unary(&mut out, &a);
    }

    // 0, 1, 2, p-2 and 2^256-1 exercise the empty ladder, the identity, one
    // squaring, the Fermat exponent, and an all-ones 256-bit ladder.
    let fixed_exps: [[u64; 4]; 5] = [
        [0, 0, 0, 0],
        [1, 0, 0, 0],
        [2, 0, 0, 0],
        {
            let mut e = Fr::MODULUS.0;
            e[0] -= 2;
            e
        },
        [u64::MAX; 4],
    ];

    out.push_str("\n# --- pow on the edge set with fixed exponents ---\n");
    for a in &edges {
        for e in &fixed_exps {
            power(&mut out, a, e);
        }
    }

    out.push_str("\n# --- pow on random bases and exponents ---\n");
    for _ in 0..RANDOM_POW {
        let a = rng.next_fr();
        let e = rng.next_exp();
        power(&mut out, &a, &e);
    }

    let path: PathBuf = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../crates/field/tests/vectors/fr_kats.txt");
    fs::write(&path, out).expect("writing the KAT file");
    println!("wrote {}", path.display());
}

fn binary(out: &mut String, a: &Fr, b: &Fr) {
    let (ha, hb) = (hex_fr(a), hex_fr(b));
    let _ = writeln!(out, "add {} {} {}", ha, hb, hex_fr(&(*a + *b)));
    let _ = writeln!(out, "sub {} {} {}", ha, hb, hex_fr(&(*a - *b)));
    let _ = writeln!(out, "mul {} {} {}", ha, hb, hex_fr(&(*a * *b)));
}

fn unary(out: &mut String, a: &Fr) {
    let ha = hex_fr(a);
    let _ = writeln!(out, "square {} {}", ha, hex_fr(&(*a * *a)));
    let inv = match a.inverse() {
        Some(i) => hex_fr(&i),
        None => {
            assert!(a.is_zero(), "only zero has no inverse");
            "none".to_string()
        }
    };
    let _ = writeln!(out, "inv {} {}", ha, inv);
}

fn power(out: &mut String, a: &Fr, e: &[u64; 4]) {
    let _ = writeln!(
        out,
        "pow {} {} {}",
        hex_fr(a),
        hex_exp(e),
        hex_fr(&a.pow(e))
    );
}
