//! The optimal ate pairing fixtures, generated against arkworks-bn254.
//!
//! One file, `crates/curve/tests/vectors/pairing_kats.txt`: the named
//! generator KAT, the infinity cases, and 120 random `(P, Q)` pairs, each
//! carrying the full pairing value `e(P, Q)`.
//!
//! # Where the expected value comes from
//!
//! Not from `ark_bn254::Bn254::pairing`. That routine's final exponentiation
//! is the Fuentes-Castañeda variant, which returns `f^(m d)` with
//! `m = 2x(6x^2 + 3x + 1)` — a fixed power of the true pairing rather than the
//! pairing — and S06's Must-be-exact 6 requires the exact `(q^12 - 1)/r`
//! power. So the oracle here is arkworks' **Miller loop** raised to the
//! literal integer exponent, which is the definition and depends on no
//! library's choice of decomposition. Both consistency checks are asserted at
//! generation time:
//!
//! * the value has order dividing `r`, and
//! * arkworks' own `pairing` is exactly this value to the `m`.
//!
//! Comparison is post-final-exponentiation only. Intermediate Miller values
//! depend on the line-evaluation and twist conventions and are deliberately
//! never compared.

use std::fmt::Write as _;

use ark_bn254::{Bn254, Fq12, Fr, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::pairing::Pairing;
use ark_ec::{AffineRepr, CurveGroup, PrimeGroup};
use ark_ff::{Field, One, PrimeField};
use num_bigint::BigUint;
use test_support::Rng;

use crate::shared::{full_final_exponent, hex_fq12, hex_g1, hex_g2};

const SEED: u64 = 20260915;

/// Acceptance 2 asks for at least a hundred random pairs.
const RANDOM_PAIRS: usize = 120;

const HEADER: &str = "\
# pairing_kats v1 -- BN254 optimal ate pairing known-answer tests
# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand
# regenerate: cargo run -p kat-gen -- pairing
# seed: 20260915 (splitmix64)
#
# A G1 point is 128 hex characters (x || y), a G2 point 256
# (x.c0 || x.c1 || y.c0 || y.c1), and an Fq12 768 (c0 || c1, each Fq6 being
# 384). All-zero is the point at infinity. Every coordinate is canonical
# 32-byte little-endian Fq, so each point token is a wire-format fixture too.
#
#   pairing_named  <name> <P> <Q> <e(P,Q)>
#   pairing_random <P> <Q> <e(P,Q)>
#
# The expected value is ark's multi_miller_loop raised to the literal integer
# (q^12 - 1)/r, NOT ark's own pairing -- which returns the Fuentes-Castaneda
# power f^(m d), m = 2x(6x^2+3x+1). The generator asserts that relationship,
# and that every value has order dividing r.
";

fn next_fr(rng: &mut Rng) -> Fr {
    Fr::from_le_bytes_mod_order(&rng.next_le32())
}

/// `e(p, q)` to the exact `(q^12 - 1)/r`, with both cross-checks asserted.
///
/// Pairs containing an infinity contribute nothing: `multi_miller_loop` drops
/// them, an empty product is one, and one to any power is one.
fn exact_pairing(p: &G1Affine, q: &G2Affine, exponent: &[u64], m: &[u64]) -> Fq12 {
    let value = Bn254::multi_miller_loop([*p], [*q]).0.pow(exponent);
    assert_eq!(
        value.pow(Fr::MODULUS.0),
        Fq12::one(),
        "a pairing value has order dividing r"
    );
    assert_eq!(
        Bn254::pairing(*p, *q).0,
        value.pow(m),
        "arkworks' pairing must be the Fuentes-Castaneda power of the exact one"
    );
    value
}

/// `m = 2x(6x^2 + 3x + 1) mod r`, exact on a value whose order divides `r`.
fn fuentes_castaneda_multiplier() -> Vec<u64> {
    let x = BigUint::from(constants::BN_PARAMETER_X);
    let m = 2u32 * &x * (6u32 * &x * &x + 3u32 * &x + 1u32);
    let reduced = m % BigUint::from(Fr::MODULUS);
    assert!(reduced > BigUint::from(1u32), "m is not trivial mod r");
    reduced.to_u64_digits()
}

fn kats() -> String {
    let mut out = String::from(HEADER);
    let mut rng = Rng::new(SEED);
    let exponent = full_final_exponent();
    let m = fuentes_castaneda_multiplier();

    let g1 = G1Affine::generator();
    let g2 = G2Affine::generator();
    let inf1 = G1Affine::identity();
    let inf2 = G2Affine::identity();

    out.push_str("\n# --- the named cases ---\n");
    for (name, p, q) in [
        ("gen_gen", g1, g2),
        ("gen_neg_gen", g1, -g2),
        ("neg_gen_gen", -g1, g2),
        ("inf_gen", inf1, g2),
        ("gen_inf", g1, inf2),
        ("inf_inf", inf1, inf2),
    ] {
        let _ = writeln!(
            out,
            "pairing_named {} {} {} {}",
            name,
            hex_g1(&p),
            hex_g2(&q),
            hex_fq12(&exact_pairing(&p, &q, &exponent, &m)),
        );
    }
    // The generator pairing is the non-degeneracy witness, so a corpus where
    // it had collapsed to one would be silently useless.
    assert_ne!(
        exact_pairing(&g1, &g2, &exponent, &m),
        Fq12::one(),
        "e(G1, G2) must not be one"
    );

    out.push_str("\n# --- random pairs ---\n");
    let mut seen = Vec::new();
    for _ in 0..RANDOM_PAIRS {
        let p = (G1Projective::generator() * next_fr(&mut rng)).into_affine();
        let q = (G2Projective::generator() * next_fr(&mut rng)).into_affine();
        assert!(!p.is_zero() && !q.is_zero(), "a random point must not be O");
        let e = exact_pairing(&p, &q, &exponent, &m);
        seen.push(hex_fq12(&e));
        let _ = writeln!(
            out,
            "pairing_random {} {} {}",
            hex_g1(&p),
            hex_g2(&q),
            hex_fq12(&e)
        );
    }
    crate::assert_distinct(&seen, "random pairing values");

    out
}

pub fn generate() {
    crate::write_vectors("crates/curve/tests/vectors/pairing_kats.txt", &kats());
}
