//! The Mercury fixtures: `crates/pcs/tests/vectors/`.
//!
//! Two files, and they are two different kinds of thing.
//!
//! * `g1_absorb_kats.txt` — the `Fr` limbs an affine G1 point absorbs as.
//!   **A genuine oracle.** Every point and every limb comes from arkworks:
//!   the point is arkworks' scalar multiplication, the limbs are its own
//!   little-endian serialization split at byte 16, and the infinity sentinel is
//!   `2^128` computed as an integer here. Nothing in this file is
//!   `crates/pcs`'s answer read back.
//!
//! * `mercury_proof.txt` — a full opening proof at `n = 2^4`.
//!   **A regression pin, not an oracle.** There is no second Mercury
//!   implementation to ask, so the proof bytes come from `pcs::open`; what they
//!   freeze is the transcript schedule, which any change to the absorb order,
//!   the tags or the encodings moves. The half of it that *is* independent is
//!   the SRS: the powers of the toy `tau` are computed with arkworks and handed
//!   to `Srs::load` as an archive, while `crates/pcs`'s own suite builds the
//!   same SRS with `crates/curve`. The two constructions have to agree or the
//!   committed proof does not replay.

use std::fmt::Write as _;

use ark_bn254::{Fq, Fq2, Fr as ArkFr, G1Affine, G1Projective, G2Affine, G2Projective};
use ark_ec::{AffineRepr, CurveGroup, PrimeGroup};
use ark_ff::{BigInteger, PrimeField};
use num_bigint::BigUint;

use field::Fr;
use pcs::{commit, open};
use poly::{MultilinearPoly, PolyBacking};
use test_support::{to_hex, Rng};
use transcript::Transcript;

/// The toy SRS secret, mirroring `crates/pcs/tests/common/mod.rs::TOY_TAU`.
/// Written down on purpose: this SRS exists to exercise the protocol.
const TOY_TAU: u64 = 0x00ab_cdef;

/// The fixture instance. Small enough that the whole witness fits in the file.
const NUM_VARS: usize = 4;
const SEED: u64 = 20260913;

pub fn generate() {
    crate::write_vectors(
        "crates/pcs/tests/vectors/g1_absorb_kats.txt",
        &absorb_kats(),
    );
    crate::write_vectors("crates/pcs/tests/vectors/mercury_proof.txt", &proof_kat());
}

// ---------------------------------------------------------------------------
// Encoding
// ---------------------------------------------------------------------------

fn fq_bytes(x: &Fq) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&x.into_bigint().to_bytes_le());
    out
}

fn g1_bytes(p: &G1Affine) -> [u8; 64] {
    let mut out = [0u8; 64];
    if p.is_zero() {
        return out;
    }
    out[..32].copy_from_slice(&fq_bytes(&p.x));
    out[32..].copy_from_slice(&fq_bytes(&p.y));
    out
}

fn g2_bytes(p: &G2Affine) -> [u8; 128] {
    let mut out = [0u8; 128];
    if p.is_zero() {
        return out;
    }
    let (x, y): (Fq2, Fq2) = (p.x, p.y);
    out[..32].copy_from_slice(&fq_bytes(&x.c0));
    out[32..64].copy_from_slice(&fq_bytes(&x.c1));
    out[64..96].copy_from_slice(&fq_bytes(&y.c0));
    out[96..].copy_from_slice(&fq_bytes(&y.c1));
    out
}

/// The four `Fr` limbs a point absorbs as, computed from arkworks alone:
/// `x` low, `x` high, `y` low, `y` high, each half a coordinate's canonical
/// little-endian encoding zero-extended to 32 bytes.
///
/// Infinity is four copies of `2^128`, the smallest value no 128-bit half can
/// take. That is `constants::G1_INFINITY_SENTINEL`, derived here rather than
/// read, so the fixture would catch the constant changing.
fn limbs(p: &G1Affine) -> [[u8; 32]; 4] {
    if p.is_zero() {
        let sentinel = BigUint::from(1u32) << 128u32;
        let mut limb = [0u8; 32];
        for (slot, byte) in limb.iter_mut().zip(sentinel.to_bytes_le()) {
            *slot = byte;
        }
        return [limb; 4];
    }
    let raw = g1_bytes(p);
    let mut out = [[0u8; 32]; 4];
    for (i, half) in raw.chunks_exact(16).enumerate() {
        out[i][..16].copy_from_slice(half);
    }
    out
}

fn limb_tokens(p: &G1Affine) -> String {
    limbs(p)
        .iter()
        .map(|l| to_hex(l))
        .collect::<Vec<_>>()
        .join(" ")
}

// ---------------------------------------------------------------------------
// g1_absorb_kats.txt
// ---------------------------------------------------------------------------

fn absorb_kats() -> String {
    let mut out = String::new();
    out.push_str(
        "\
# G1 transcript absorption -- docs/spec/mercury.md section 4.
# Generated by `cargo run -p kat-gen -- pcs`, from ark-bn254. Do not edit.
#
# A point absorbs as four Fr limbs: x low, x high, y low, y high, where the
# halves are the 128-bit halves of the coordinate's canonical little-endian
# encoding. Infinity absorbs four copies of 2^128.
#
# Records, one token per value, all hex, all canonical little-endian:
#   single <G1 64B> <limb0> <limb1> <limb2> <limb3>
#   pair   <G1 64B> <G1 64B> <limb0> .. <limb7>
# A `pair` is ONE typed message of eight limbs, not two messages of four.
",
    );

    let mut rng = Rng::new(SEED);
    let mut points = vec![G1Affine::identity(), G1Affine::generator()];
    for _ in 0..6 {
        let k = ArkFr::from_le_bytes_mod_order(&rng.next_le32());
        points.push((G1Projective::generator() * k).into_affine());
    }

    for p in &points {
        writeln!(out, "single {} {}", to_hex(&g1_bytes(p)), limb_tokens(p))
            .expect("writing to a String");
    }

    // The list case: a real pair, and a pair containing infinity, so the
    // sentinel is exercised inside a list as well as alone.
    for (a, b) in [(points[1], points[2]), (points[0], points[3])] {
        writeln!(
            out,
            "pair {} {} {} {}",
            to_hex(&g1_bytes(&a)),
            to_hex(&g1_bytes(&b)),
            limb_tokens(&a),
            limb_tokens(&b)
        )
        .expect("writing to a String");
    }

    out
}

// ---------------------------------------------------------------------------
// mercury_proof.txt
// ---------------------------------------------------------------------------

fn proof_kat() -> String {
    let n = 1usize << NUM_VARS;

    // The SRS, built with arkworks and handed to `Srs::load` as an archive.
    let tau = ArkFr::from(TOY_TAU);
    let mut scalars = Vec::with_capacity(n);
    let mut acc = ArkFr::from(1u64);
    for _ in 0..n {
        scalars.push(acc);
        acc *= tau;
    }
    let mut archive = Vec::new();
    archive.extend_from_slice(b"APOGESRS");
    archive.extend_from_slice(&1u32.to_le_bytes());
    archive.extend_from_slice(&(NUM_VARS as u32).to_le_bytes());
    archive.extend_from_slice(&(n as u64).to_le_bytes());
    archive.extend_from_slice(&g2_bytes(&G2Affine::generator()));
    archive.extend_from_slice(&g2_bytes(&(G2Projective::generator() * tau).into_affine()));
    for s in &scalars {
        archive.extend_from_slice(&g1_bytes(&(G1Projective::generator() * s).into_affine()));
    }
    let path = std::env::temp_dir().join(format!("apogee-kat-gen-{}.srs", std::process::id()));
    std::fs::write(&path, &archive).expect("writing the toy archive");
    let srs = srs::Srs::load(&path).expect("the toy archive loads");
    std::fs::remove_file(&path).ok();

    // The witness and the point, from the seeded stream.
    let mut rng = Rng::new(SEED + 1);
    let values: Vec<Fr> = (0..n).map(|_| next_fr(&mut rng)).collect();
    let point: Vec<Fr> = (0..NUM_VARS).map(|_| next_fr(&mut rng)).collect();

    let f = MultilinearPoly::new(PolyBacking::Fr(values.clone()));
    let cm = commit(&srs, &f).expect("commit");
    let mut tr = Transcript::new();
    let (v, proof) = open(&srs, &f, &cm, &point, &mut tr).expect("open");

    // The raw duplex sample the transcript yields once the opening is over. It
    // is a function of the terminal sponge state, so it pins every step of the
    // schedule — including the squeeze positions of challenges nothing reads
    // back, which the proof bytes alone cannot see.
    let probe = tr.sample();

    let mut out = String::new();
    out.push_str(
        "\
# A full Mercury opening proof at n = 2^4 -- docs/spec/mercury.md section 8.
# Generated by `cargo run -p kat-gen -- pcs`. Do not edit.
#
# A REGRESSION PIN, not an oracle: the proof bytes are `pcs::open`'s own
# output, and what they freeze is the transcript schedule. The SRS is the
# independent half -- its powers are arkworks', while the test rebuilds the
# same SRS with `crates/curve`.
#
# Records, one token per value, all hex, all canonical little-endian:
#   tau        <Fr 32B>          the toy SRS secret; the archive is 2^numvars powers of it
#   numvars    <decimal>
#   value      <index> <Fr 32B>  one evaluation of f, in index order
#   point      <index> <Fr 32B>  one coordinate of u, in variable order
#   claim      <Fr 32B>          v = fhat(u)
#   commitment <G1 64B>
#   proof      <704B>            8 G1 points then 6 Fr values, in field order
",
    );
    writeln!(out, "tau {}", to_hex(&fr_bytes(&tau))).expect("writing to a String");
    writeln!(out, "numvars {NUM_VARS}").expect("writing to a String");
    for (i, x) in values.iter().enumerate() {
        writeln!(out, "value {i} {}", to_hex(&x.to_bytes())).expect("writing to a String");
    }
    for (i, x) in point.iter().enumerate() {
        writeln!(out, "point {i} {}", to_hex(&x.to_bytes())).expect("writing to a String");
    }
    writeln!(out, "claim {}", to_hex(&v.to_bytes())).expect("writing to a String");
    writeln!(out, "commitment {}", to_hex(&cm.0.to_bytes())).expect("writing to a String");
    writeln!(out, "proof {}", to_hex(&proof.to_bytes())).expect("writing to a String");
    writeln!(out, "probe {}", to_hex(&probe.to_bytes())).expect("writing to a String");
    out
}

fn fr_bytes(x: &ArkFr) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(&x.into_bigint().to_bytes_le());
    out
}

/// The same canonical sampler `crates/pcs`'s suite uses: 32 little-endian
/// bytes with the top two bits cleared, rejected rather than reduced.
fn next_fr(rng: &mut Rng) -> Fr {
    loop {
        let mut b = rng.next_le32();
        b[31] &= 0x3f;
        if let Some(x) = Fr::from_bytes(&b) {
            return x;
        }
    }
}
