//! The multilinear-polynomial fixtures, generated against `ark-poly`.
//!
//! Two files, both written to `crates/poly/tests/vectors/`:
//!
//! * `poly_kats.txt` — one fixed seeded 10-variable polynomial, its bind chain,
//!   20 evaluations, and `eq_table` on prefixes of the bind challenges.
//! * `evaluate_diff.txt` — a 100-case differential corpus at `n <= 12` across
//!   all five backings.
//!
//! Every expected value here comes from arkworks: bind chains from
//! `MultilinearExtension::fix_variables`, evaluations from
//! `Polynomial::evaluate`, and `eq` from the direct product formula. None of
//! it is `crates/poly`'s own answer read back.

use std::fmt::Write as _;

use ark_bn254::Fr;
use ark_ff::{BigInteger, One, PrimeField};
use ark_poly::{DenseMultilinearExtension, MultilinearExtension, Polynomial};
use test_support::{sha256, to_hex, Rng};

/// The fixed 10-variable polynomial of `poly_kats.txt`, and its challenges.
const KAT_SEED: u64 = 20260907;
const KAT_VARS: usize = 10;
const KAT_POINTS: usize = 20;
/// `eq_table` is committed on the challenge prefixes `r[..k]` for `k <= this`.
/// Larger `k` is checked in-process against `eq_eval`, which is stronger than
/// another 130 KB of hex.
const KAT_EQ_PREFIX: usize = 6;

/// The differential corpus of `evaluate_diff.txt`. Case `i` is seeded
/// `DIFF_SEED + i`, has `i % 13` variables, and uses backing `i % 5`.
const DIFF_SEED: u64 = 20260908;
const DIFF_CASES: usize = 100;

/// The five backings, in the order the corpus cycles through them.
const BACKINGS: [&str; 5] = ["u1", "u8", "u16", "u32", "fr"];

fn hex_fr(x: &Fr) -> String {
    let bytes = x.into_bigint().to_bytes_le();
    assert_eq!(bytes.len(), 32, "Fr must serialize to 32 bytes");
    to_hex(&bytes)
}

/// A field element from four `u64` draws read as one 256-bit little-endian
/// integer, reduced mod p. `crates/poly`'s tests rebuild the same value from
/// the same draws through `Fr::from_u64`, and check the two agree.
fn next_fr(rng: &mut Rng) -> Fr {
    Fr::from_le_bytes_mod_order(&rng.next_le32())
}

/// One entry of a case's table, drawn in the native width of `backing` and
/// returned already lifted. The draw rule is the file header's, and
/// `crates/poly`'s tests reproduce it to rebuild the table.
fn next_entry(rng: &mut Rng, backing: &str) -> Fr {
    match backing {
        "u1" => Fr::from(rng.next_u64() & 1),
        "u8" => Fr::from(rng.next_u64() as u8 as u64),
        "u16" => Fr::from(rng.next_u64() as u16 as u64),
        "u32" => Fr::from(rng.next_u64() as u32 as u64),
        "fr" => next_fr(rng),
        other => panic!("unknown backing {other}"),
    }
}

/// `eq(r, y)` for a cube vertex `y`, by the direct product formula — a
/// different algorithm from the iterative doubling `poly::eq_table` uses.
fn eq_at_vertex(r: &[Fr], y: usize) -> Fr {
    let mut acc = Fr::one();
    for (j, rj) in r.iter().enumerate() {
        acc *= if (y >> j) & 1 == 1 {
            *rj
        } else {
            Fr::one() - rj
        };
    }
    acc
}

pub fn generate() {
    crate::write_vectors("crates/poly/tests/vectors/poly_kats.txt", &kats());
    crate::write_vectors(
        "crates/poly/tests/vectors/evaluate_diff.txt",
        &differential(),
    );
}

// ---------------------------------------------------------------------------
// poly_kats.txt
// ---------------------------------------------------------------------------

fn kats() -> String {
    let mut rng = Rng::new(KAT_SEED);
    let mut out = String::new();

    out.push_str("# poly_kats v1 -- multilinear polynomial known-answer tests\n");
    out.push_str(
        "# generated by tools/kat-gen against ark-poly / ark-bn254 0.6; do not edit by hand\n",
    );
    out.push_str("# regenerate: cargo run -p kat-gen\n");
    out.push_str("# seed: 20260907 (splitmix64)\n");
    out.push_str("#\n");
    out.push_str("# Field elements are 32 bytes of lowercase hex in little-endian byte order,\n");
    out.push_str("# exactly as Fr::to_bytes emits them. Source values are u32 and are written\n");
    out.push_str("# as 8 hex digits big-endian, because a small-typed entry is a number.\n");
    out.push_str("#\n");
    out.push_str("# The evaluation at y in {0,1}^n sits at index sum_j y_j 2^j: variable 0 is\n");
    out.push_str("# the low bit. bind(r) fixes variable 0.\n");
    out.push_str("#\n");
    out.push_str("#   source    <backing> <num_vars>   the polynomial under test\n");
    out.push_str("#   value     <index> <u32>          one source entry, in index order\n");
    out.push_str("#   challenge <index> <hex>          one bind challenge, in bind order\n");
    out.push_str("#   bind      <k> <index> <hex>      the table after binding challenges 0..k\n");
    out.push_str("#   point     <case> <index> <hex>   one coordinate of an evaluation point\n");
    out.push_str("#   result    <case> <hex>           evaluate(point of that case)\n");
    out.push_str("#   eq        <k> <index> <hex>      eq_table(challenges[..k])\n");

    // The source polynomial: u32 values, so the fixture exercises the lift.
    let source: Vec<u32> = (0..1usize << KAT_VARS)
        .map(|_| rng.next_u64() as u32)
        .collect();
    let _ = writeln!(out, "\nsource u32 {KAT_VARS}");
    for (i, v) in source.iter().enumerate() {
        let _ = writeln!(out, "value {i} {v:08x}");
    }

    let lifted: Vec<Fr> = source.iter().map(|v| Fr::from(*v as u64)).collect();
    let mle = DenseMultilinearExtension::from_evaluations_vec(KAT_VARS, lifted);

    let challenges: Vec<Fr> = (0..KAT_VARS).map(|_| next_fr(&mut rng)).collect();
    out.push('\n');
    for (i, r) in challenges.iter().enumerate() {
        let _ = writeln!(out, "challenge {i} {}", hex_fr(r));
    }

    // The bind chain, taken from the original polynomial each time, so a bug in
    // arkworks' incremental path could not hide one in ours.
    for k in 1..=KAT_VARS {
        let folded = mle.fix_variables(&challenges[..k]);
        assert_eq!(folded.num_vars, KAT_VARS - k);
        out.push('\n');
        for (i, v) in folded.evaluations.iter().enumerate() {
            let _ = writeln!(out, "bind {k} {i} {}", hex_fr(v));
        }
    }

    out.push('\n');
    for case in 0..KAT_POINTS {
        let point: Vec<Fr> = (0..KAT_VARS).map(|_| next_fr(&mut rng)).collect();
        for (i, c) in point.iter().enumerate() {
            let _ = writeln!(out, "point {case} {i} {}", hex_fr(c));
        }
        let _ = writeln!(out, "result {case} {}", hex_fr(&mle.evaluate(&point)));
    }

    for k in 0..=KAT_EQ_PREFIX {
        out.push('\n');
        for y in 0..1usize << k {
            let _ = writeln!(
                out,
                "eq {k} {y} {}",
                hex_fr(&eq_at_vertex(&challenges[..k], y))
            );
        }
    }

    out
}

// ---------------------------------------------------------------------------
// evaluate_diff.txt
// ---------------------------------------------------------------------------

fn differential() -> String {
    let mut out = String::new();

    out.push_str("# evaluate_diff v1 -- MultilinearPoly::evaluate against ark-poly\n");
    out.push_str(
        "# generated by tools/kat-gen against ark-poly / ark-bn254 0.6; do not edit by hand\n",
    );
    out.push_str("# regenerate: cargo run -p kat-gen\n");
    out.push_str("# seed: 20260908 (splitmix64); case i draws from Rng::new(seed + i)\n");
    out.push_str("#\n");
    out.push_str("# Field elements are 32 bytes of lowercase hex, little-endian canonical.\n");
    out.push_str("#\n");
    out.push_str("# Case i has `i % 13` variables and backing BACKINGS[i % 5]. Its 2^n table\n");
    out.push_str("# entries are drawn in index order, one draw each, as\n");
    out.push_str("#\n");
    out.push_str("#   u1  -> next_u64() & 1        u16 -> next_u64() as u16\n");
    out.push_str("#   u8  -> next_u64() as u8      u32 -> next_u64() as u32\n");
    out.push_str("#   fr  -> next_le32() read as a 256-bit little-endian integer mod p\n");
    out.push_str("#          (four draws)\n");
    out.push_str("#\n");
    out.push_str("# The table is not written out -- 100 cases of up to 4096 entries is a\n");
    out.push_str("# megabyte of hex -- so `digest` pins it instead: SHA-256 over the lifted\n");
    out.push_str("# entries, 32 canonical little-endian bytes each, concatenated in index\n");
    out.push_str("# order. A replay that rebuilds a different table fails on the digest\n");
    out.push_str("# rather than on the result.\n");
    out.push_str("#\n");
    out.push_str("#   case   <i> <backing> <num_vars> <digest>\n");
    out.push_str("#   point  <i> <index> <hex>          one coordinate, drawn after the table\n");
    out.push_str("#   result <i> <hex>                  ark-poly's evaluate at that point\n");

    let mut seen: Vec<String> = Vec::new();
    for i in 0..DIFF_CASES {
        let backing = BACKINGS[i % BACKINGS.len()];
        let num_vars = i % 13;
        let mut rng = Rng::new(DIFF_SEED + i as u64);

        let table: Vec<Fr> = (0..1usize << num_vars)
            .map(|_| next_entry(&mut rng, backing))
            .collect();
        let mut bytes = Vec::with_capacity(32 * table.len());
        for v in &table {
            bytes.extend_from_slice(&v.into_bigint().to_bytes_le());
        }
        let digest = to_hex(&sha256(&bytes));

        let point: Vec<Fr> = (0..num_vars).map(|_| next_fr(&mut rng)).collect();
        let mle = DenseMultilinearExtension::from_evaluations_vec(num_vars, table);

        let _ = writeln!(out, "\ncase {i} {backing} {num_vars} {digest}");
        for (j, c) in point.iter().enumerate() {
            let _ = writeln!(out, "point {i} {j} {}", hex_fr(c));
        }
        let result = hex_fr(&mle.evaluate(&point));
        let _ = writeln!(out, "result {i} {result}");
        // A generator whose input stream had collapsed would still write 100
        // cases that all "match", so every table and every answer has to be its
        // own. Below 32 entries a repeat is legitimate -- two one-bit tables
        // agree half the time -- so the check starts where it is meaningful.
        if num_vars >= 5 {
            seen.push(digest);
            seen.push(result);
        }
    }

    let mut sorted = seen.clone();
    sorted.sort();
    sorted.dedup();
    assert_eq!(
        sorted.len(),
        seen.len(),
        "the corpus must not repeat a table or an answer"
    );
    out
}
