//! `crates/program`'s fixtures: a mul-free program, and the pinned program
//! identities.
//!
//! The identities are the first fixture here generated by the code it tests,
//! the way `crates/pcs`'s proof fixture is: there is no second preprocessor to
//! ask. What they pin is the recipe — the table construction, the column
//! order, the digest's message schedule — so any change to one moves them.
//! They need the PSE ceremony file, which is gitignored; without it this group
//! says so and writes nothing for them, exactly as the `srs` group does.

use std::path::PathBuf;

use loader::load_elf;
use program::{decode_program, program_identity, ProgramParams};
use srs::Srs;

use crate::isa::{b, i, j, r, s, u};
use crate::loader::ElfBuilder;
use crate::write_vectors;

/// The ceremony file every identity is taken over.
pub const PTAU: &str = "assets/ptau/ppot_0080_24.ptau";

pub fn generate() {
    mul_free();
    identities();
}

/// A program with no M and no A instruction: base loads and stores, both
/// memory families, a branch, a jump, an ecall — so its derived config holds
/// every instruction family except mul/div and atomics.
fn mul_free() {
    let words = [
        i(10, 0, 0b000, 10, 0x13),     // addi a0, zero, 10
        u(0x12, 5, 0x37),              // lui t0, 0x12
        u(0, 6, 0x17),                 // auipc t1, 0
        s(0, 10, 2, 0b010),            // sw a0, 0(sp)
        i(0, 2, 0b010, 11, 0x03),      // lw a1, 0(sp)
        i(1, 2, 0b100, 12, 0x03),      // lbu a2, 1(sp)
        r(0, 12, 11, 0b100, 13, 0x33), // xor a3, a1, a2
        i(2, 13, 0b001, 13, 0x13),     // slli a3, a3, 2
        b(8, 0, 13, 0b000),            // beq a3, zero, +8
        j(4, 0),                       // jal zero, +4
        i(93, 0, 0b000, 17, 0x13),     // addi a7, zero, 93
        0x0000_0073,                   // ecall
    ];
    let text: Vec<u8> = words.iter().flat_map(|w| w.to_le_bytes()).collect();
    std::fs::create_dir_all(repo_root().join("crates/program/tests/vectors"))
        .expect("creating crates/program/tests/vectors");
    crate::write_bytes(
        "crates/program/tests/vectors/mul_free.elf",
        &ElfBuilder::rv32_exec(&text).build(),
    );
}

/// fib's identity at the default parameters and at the smallest menu height.
fn identities() {
    let ptau = repo_root().join(PTAU);
    if !ptau.exists() {
        println!("skipped crates/program/tests/vectors/identity.txt: {PTAU} is absent");
        return;
    }
    let srs = Srs::from_ptau(&ptau, 22).expect("the ceremony file ingests at power 22");
    let fib = std::fs::read(repo_root().join("crates/loader/tests/vectors/fib.elf"))
        .expect("reading fib.elf");
    let image = load_elf(&fib).expect("fib loads");

    let smallest = ProgramParams {
        heights: [constants::family::HEIGHT_MENU[0]; constants::family::COUNT as usize],
        ..ProgramParams::defaults()
    };
    let mut body = String::new();
    for (label, params) in [
        ("default", ProgramParams::defaults()),
        ("smallest", smallest),
    ] {
        let (tables, config) = decode_program(&image, &params).expect("fib decodes");
        let identity = program_identity(&tables, &config, &srs);
        body.push_str(&format!(
            "fib {label} {}\n",
            test_support::to_hex(&identity.to_bytes())
        ));
    }
    write_vectors(
        "crates/program/tests/vectors/identity.txt",
        &format!(
            "# guests/fib's program identity. Generated by `cargo run -p kat-gen --\n\
             # program`, which needs {PTAU}. Do not edit.\n\
             #\n\
             # A regression pin, generated by crates/program itself: it freezes the\n\
             # table construction and the digest recipe. `default` is\n\
             # ProgramParams::defaults(); `smallest` puts every family at 2^16.\n\
             # Fields: guest, parameters, identity (canonical 32-byte LE).\n\
             #\n\
             # ceremony {}\n\
             {body}",
            test_support::to_hex(&srs.g1()[1].to_bytes())
        ),
    );
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}
