//! `crates/program`'s fixtures: a mul-free program, the pinned program
//! identities, and the packed generic table's pinned commitments.
//!
//! The identities are the first fixture here generated by the code it tests,
//! the way `crates/pcs`'s proof fixture is: there is no second preprocessor to
//! ask. What they pin is the recipe — the table construction, the column
//! order, the digest's message schedule — so any change to one moves them.
//! They need the PSE ceremony file, which is gitignored; without it this group
//! says so and writes nothing for them, exactly as the `srs` group does.

use std::path::PathBuf;

use loader::load_elf;
use program::lookup_tables::{generic_commitments, generic_table as generic_table_columns};
use program::{decode_program, program_identity, ProgramParams};
use srs::Srs;

use crate::isa::{b, i, j, r, s, u};
use crate::loader::ElfBuilder;
use crate::write_vectors;

/// The ceremony file every identity, and the generic table's commitments, are
/// taken over.
pub const PTAU: &str = "assets/ptau/ppot_0080_24.ptau";

pub fn generate() {
    mul_free();
    identities();
}

/// A program with no M and no A instruction: base loads and stores, both
/// memory families, a branch, a jump, an ecall — so its derived config holds
/// every instruction family except mul/div and atomics.
fn mul_free() {
    let words = [
        i(10, 0, 0b000, 10, 0x13),     // addi a0, zero, 10
        u(0x12, 5, 0x37),              // lui t0, 0x12
        u(0, 6, 0x17),                 // auipc t1, 0
        s(0, 10, 2, 0b010),            // sw a0, 0(sp)
        i(0, 2, 0b010, 11, 0x03),      // lw a1, 0(sp)
        i(1, 2, 0b100, 12, 0x03),      // lbu a2, 1(sp)
        r(0, 12, 11, 0b100, 13, 0x33), // xor a3, a1, a2
        i(2, 13, 0b001, 13, 0x13),     // slli a3, a3, 2
        b(8, 0, 13, 0b000),            // beq a3, zero, +8
        j(4, 0),                       // jal zero, +4
        i(93, 0, 0b000, 17, 0x13),     // addi a7, zero, 93
        0x0000_0073,                   // ecall
    ];
    let text: Vec<u8> = words.iter().flat_map(|w| w.to_le_bytes()).collect();
    std::fs::create_dir_all(repo_root().join("crates/program/tests/vectors"))
        .expect("creating crates/program/tests/vectors");
    crate::write_bytes(
        "crates/program/tests/vectors/mul_free.elf",
        &ElfBuilder::rv32_exec(&text).build(),
    );
}

/// fib's identity at the default parameters and at the smallest menu height,
/// and the packed generic table's commitments: both over the ceremony.
fn identities() {
    let ptau = repo_root().join(PTAU);
    if !ptau.exists() {
        println!(
            "skipped crates/program/tests/vectors/identity.txt and generic_table.txt: {PTAU} \
             is absent"
        );
        return;
    }
    let srs = Srs::from_ptau(&ptau, 22).expect("the ceremony file ingests at power 22");
    let fib = std::fs::read(repo_root().join("crates/loader/tests/vectors/fib.elf"))
        .expect("reading fib.elf");
    let image = load_elf(&fib).expect("fib loads");

    // The menu's **second** entry since S21, which opens with `2^8` for the
    // delegation families: a delegation row is an invocation, not a halfword,
    // so 256 rows is a sensible table there and no guest's code fits in 256
    // halfwords anywhere else (`docs/spec/delegation.md` §9). The pinned
    // identity is fib's at a uniform `2^16` and must stay that, so the height
    // is asserted rather than left to an index.
    let smallest_height = constants::family::HEIGHT_MENU[1];
    assert_eq!(
        smallest_height,
        1 << 16,
        "the menu's second entry is no longer 2^16, and identity.txt pins 2^16"
    );
    let smallest = ProgramParams {
        heights: [smallest_height; constants::family::COUNT as usize],
        ..ProgramParams::defaults()
    };
    generic_table(&srs);
    let mut body = String::new();
    for (label, params) in [
        ("default", ProgramParams::defaults()),
        ("smallest", smallest),
    ] {
        let (tables, config) = decode_program(&image, &params).expect("fib decodes");
        let identity = program_identity(&image, &tables, &config, &srs);
        body.push_str(&format!(
            "fib {label} {}\n",
            test_support::to_hex(&identity.to_bytes())
        ));
    }
    write_vectors(
        "crates/program/tests/vectors/identity.txt",
        &format!(
            "# guests/fib's program identity. Generated by `cargo run -p kat-gen --\n\
             # program`, which needs {PTAU}. Do not edit.\n\
             #\n\
             # A regression pin, generated by crates/program itself: it freezes the\n\
             # table construction, the image column and the digest recipe. `default` is\n\
             # ProgramParams::defaults(); `smallest` puts every family at 2^16.\n\
             # Fields: guest, parameters, identity (canonical 32-byte LE).\n\
             #\n\
             # ceremony {}\n\
             {body}",
            test_support::to_hex(&srs.g1()[1].to_bytes())
        ),
    );
}

/// The packed generic table's three commitments over the ceremony — what every
/// verifying key carries and its SRS digest covers
/// (`docs/spec/jump-branch-slt.md` §6) — after checking that the table over
/// each menu height it fits commits to the same three points, which is what
/// lets one set serve every height.
fn generic_table(srs: &Srs) {
    let points = generic_commitments(srs);
    for &height in &constants::family::HEIGHT_MENU {
        let log = height.trailing_zeros();
        if log < program::lookup_tables::GENERIC_LOG_HEIGHT {
            continue;
        }
        for (column, point) in generic_table_columns(log).iter().zip(&points) {
            let at = pcs::commit(srs, column)
                .expect("committing the generic table")
                .0;
            assert_eq!(&at, point, "the generic table commits alike at 2^{log}");
        }
    }
    let body: Vec<String> = points
        .iter()
        .map(|p| test_support::to_hex(&p.to_bytes()))
        .collect();
    write_vectors(
        "crates/program/tests/vectors/generic_table.txt",
        &format!(
            "# The packed generic table's commitments over PSE's ceremony. Generated by\n\
             # `cargo run -p kat-gen -- program`, which needs {PTAU}. Do not edit.\n\
             #\n\
             # A regression pin, generated by crates/program itself: the key, value and\n\
             # result columns' commitments (64-byte canonical G1 encodings), which every\n\
             # verifying key carries and its SRS digest covers. The generator checked\n\
             # that the table commits to these points at 2^18, 2^20 and 2^22 alike.\n\
             #\n\
             # ceremony {}\n\
             {}\n",
            test_support::to_hex(&srs.g1()[1].to_bytes()),
            body.join(" ")
        ),
    );
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}
