//! The `tape` group: the global commit phase's absorb sequence for S20's
//! two-shard statement, `crates/checker/tests/vectors/global_tape.txt`.
//!
//!     cargo run -p kat-gen -- tape
//!
//! A tape is a statement about the **script** a transcript runs — one line per
//! typed message, its tag and its payload length, never its values — so it is
//! a function of the statement's *shape* alone: the family count, the shard
//! counts, the window list and each shard's commitment-list width. This
//! generator builds that shape, with placeholder points, and writes the tape
//! `checker::check_global_tape` returns: the tape the real phase ran, **after**
//! it was diffed against the frozen pre-fork order of
//! `docs/spec/shard-proof.md` §2, which `checker::expected_global_tape` writes
//! out independently.
//!
//! The shape is `guests/shards`': `ADD_SUB_LUI_AUIPC` at `2^20` in two shards,
//! `JUMP_BRANCH_SLT` at `2^20` in one, `INIT_TEARDOWN` at `2^16` in one, and
//! `ZERO_WINDOWS` at `2^16` in none — the guest touches no RAM. The proving
//! suite asserts the real run's tape is this file.

use constants::family;
use constraints::family_circuit;
use verifier_core::{
    identity_digest, srs_digest, BoundaryFinals, PublicInputs, VerifyingKey, VmConfig,
};

/// A stand-in `G1` encoding. A tape carries no values, only lengths.
const POINT: [u8; 64] = [0; 64];

pub fn generate() {
    let config = VmConfig {
        families: vec![
            (family::ADD_SUB_LUI_AUIPC, 1 << 20),
            (family::JUMP_BRANCH_SLT, 1 << 20),
            (family::INIT_TEARDOWN, 1 << 16),
            (family::ZERO_WINDOWS, 1 << 16),
            // S-IO's three, in every `VmConfig`
            // (`docs/spec/public-values.md` §4).
            (family::PUBLIC_INPUT, family::PUBLIC_WINDOW_HEIGHT),
            (family::PUBLIC_OUTPUT, family::PUBLIC_WINDOW_HEIGHT),
            (family::ADVICE_WINDOWS, 1 << 16),
        ],
        bytecode_size_words: family::DEFAULT_BYTECODE_SIZE_WORDS,
    };
    let circuits: Vec<_> = config
        .families
        .iter()
        .map(|(f, h)| {
            family_circuit(*f, h.trailing_zeros())
                .unwrap_or_else(|| panic!("the registry has family {f} at height {h}"))
        })
        .collect();
    let widths: Vec<(u32, usize)> = circuits
        .iter()
        .map(|c| (c.family, c.artifact.memory.len()))
        .collect();
    let width = |family: u32| -> usize {
        widths
            .iter()
            .find(|(f, _)| *f == family)
            .expect("a config family")
            .1
    };
    // One setup list per family, each as long as its circuit's `S` layout
    // minus the generic table's, which the key carries once.
    let setup: Vec<Vec<[u8; 64]>> = circuits
        .iter()
        .map(|c| {
            let generic = match c.reads_generic_table() {
                true => constants::generic_table::WIDTH,
                false => 0,
            };
            vec![POINT; c.artifact.setup.len() - generic]
        })
        .collect();
    let generic_table = [POINT; constants::generic_table::WIDTH];
    let srs_verifier = [0u8; 320];
    let entry_pc = 0x1_0000;
    let vk = VerifyingKey {
        code_version: family::CODE_VERSION,
        entry_pc,
        identity: identity_digest(family::CODE_VERSION, &config, entry_pc, &setup),
        config,
        setup_commitments: setup,
        srs_verifier,
        generic_table,
        srs_digest: srs_digest(&srs_verifier, &generic_table),
        circuits,
    };
    // Statement order: INIT_TEARDOWN, ZERO_WINDOWS (none), then ascending.
    let shard_counts = vec![2, 1, 1, 0, 1, 1, 0];
    let statement = PublicInputs {
        input: Vec::new(),
        output: Vec::new(),
        exit_status: 2,
        shard_counts,
        windows: Vec::new(),
        boundary: BoundaryFinals {
            reg_ts: [0; 32],
            pc_ts: 0,
            reg_values: [0; 31],
        },
        memory_commitments: vec![
            vec![POINT; width(family::INIT_TEARDOWN)],
            vec![POINT; width(family::ADD_SUB_LUI_AUIPC)],
            vec![POINT; width(family::ADD_SUB_LUI_AUIPC)],
            vec![POINT; width(family::JUMP_BRANCH_SLT)],
            vec![POINT; width(family::PUBLIC_INPUT)],
            vec![POINT; width(family::PUBLIC_OUTPUT)],
        ],
        memory_roots: vec![[field::Fr::ZERO; 2]; 6],
    };
    let lines = checker::check_global_tape(&vk, &statement)
        .expect("the global commit phase keeps the frozen pre-fork order");
    let mut text = String::from(
        "# The global commit phase's absorb sequence for S20's two-shard statement,\n\
         # G1-G11 of docs/spec/shard-proof.md section 2. One line per typed message:\n\
         # `absorb <TAG> <payload field elements>` or `squeeze <TAG>`. Generated by\n\
         # `cargo run -p kat-gen -- tape`; see tools/kat-gen/src/tape.rs.\n",
    );
    for line in lines {
        text.push_str(&line);
        text.push('\n');
    }
    crate::write_bytes(
        "crates/checker/tests/vectors/global_tape.txt",
        text.as_bytes(),
    );
}
