//! The Fq6 and Fq12 fixtures, generated against arkworks-bn254.
//!
//! Two files, both written to `crates/curve/tests/vectors/`:
//!
//! * `fq6_kats.txt` — Fq6 arithmetic: an edge grid, 1,000 random vectors,
//!   the Frobenius at every power `0..6`, and `pow`.
//! * `fq12_kats.txt` — the same for Fq12, with `conjugate` in place of
//!   `mul_by_nonresidue`, the Frobenius at every power `0..12`, and the
//!   final exponentiation.
//!
//! # Encoding
//!
//! One token per value, extending the convention `curve.rs` set: 64 hex
//! characters of canonical little-endian `Fq`, concatenated in coefficient
//! order. So an `Fq2` is 128 characters, an `Fq6` 384 written
//! `c0 || c1 || c2`, and an `Fq12` 768 written `c0 || c1`. A value that does
//! not exist is the token `none`, so every line kind has a fixed arity.
//!
//! # The final exponentiation is the literal exponent
//!
//! `fq12_final_exp` raises to `(q^12 - 1)/r` computed as an integer, **not**
//! to whatever `ark_bn254::Bn254::final_exponentiation` returns. arkworks
//! uses the Fuentes-Castañeda variant, which produces `f^(m d)` for a fixed
//! `m = 2x(6x^2 + 3x + 1)` rather than `f^d`, and S06 requires the exact
//! power. The relationship is asserted here rather than assumed, so a change
//! in either direction is caught at generation time.

use std::fmt::Write as _;

use ark_bn254::{Fq, Fq12, Fq2, Fq6, Fr};
use ark_ff::{AdditiveGroup, Field, One, PrimeField, Zero};
use num_bigint::BigUint;
use test_support::Rng;

use crate::shared::{
    full_final_exponent, hex_exp, hex_fq12, hex_fq6, opt_fq12, opt_fq6, FIXED_EXPONENTS,
};

const FQ6_SEED: u64 = 20260913;
const FQ12_SEED: u64 = 20260914;

/// Acceptance 1 asks for at least a thousand random vectors per operation.
const RANDOM_VECTORS: usize = 1_000;
/// Elements carried through every Frobenius power, on top of the edge set.
const FROBENIUS_SAMPLES: usize = 12;
/// Inputs to the exact `(q^12 - 1)/r` exponentiation. Not an Acceptance-1 op,
/// and each one costs a 2,790-bit ladder on both sides, so this is a smaller
/// corpus than the arithmetic above.
const FINAL_EXP_SAMPLES: usize = 200;

// ---------------------------------------------------------------------------
// Sampling
// ---------------------------------------------------------------------------

fn next_fq(rng: &mut Rng) -> Fq {
    Fq::from_le_bytes_mod_order(&rng.next_le32())
}

fn next_fq2(rng: &mut Rng) -> Fq2 {
    Fq2::new(next_fq(rng), next_fq(rng))
}

fn next_fq6(rng: &mut Rng) -> Fq6 {
    Fq6::new(next_fq2(rng), next_fq2(rng), next_fq2(rng))
}

fn next_fq12(rng: &mut Rng) -> Fq12 {
    Fq12::new(next_fq6(rng), next_fq6(rng))
}

fn xi() -> Fq2 {
    let xi = <ark_bn254::Fq6Config as ark_ff::fields::Fp6Config>::NONRESIDUE;
    assert_eq!(xi, Fq2::new(Fq::from(9u64), Fq::one()), "xi must be 9 + u");
    xi
}

/// Eight Fq6 edges: zero, one, the two pure powers of `v`, the nonresidue
/// itself, and three elements with a zero sub-component in each position.
fn fq6_edges() -> Vec<Fq6> {
    let (z, o, m) = (Fq2::ZERO, Fq2::ONE, -Fq2::ONE);
    let u = Fq2::new(Fq::ZERO, Fq::one());
    vec![
        Fq6::new(z, z, z),
        Fq6::new(o, z, z),
        Fq6::new(z, o, z),
        Fq6::new(z, z, o),
        Fq6::new(xi(), z, z),
        Fq6::new(o, z, o),
        Fq6::new(z, o, o),
        Fq6::new(m, u, -u),
    ]
}

/// Eight Fq12 edges, on the same principle one level up.
fn fq12_edges() -> Vec<Fq12> {
    let e = fq6_edges();
    let (z, o) = (Fq6::ZERO, Fq6::ONE);
    vec![
        Fq12::new(z, z),
        Fq12::new(o, z),
        Fq12::new(z, o),
        Fq12::new(o, o),
        Fq12::new(e[2], z),
        Fq12::new(z, e[2]),
        Fq12::new(e[4], -o),
        Fq12::new(e[5], e[7]),
    ]
}

// ---------------------------------------------------------------------------
// fq6_kats.txt
// ---------------------------------------------------------------------------

const FQ6_HEADER: &str = "\
# fq6_kats v1 -- BN254 Fq6 known-answer tests
# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand
# regenerate: cargo run -p kat-gen -- tower
# seed: 20260913 (splitmix64)
#
# Fq6 = Fq2[v]/(v^3 - xi), xi = 9 + u. One token per value: 384 hex characters
# written c0 || c1 || c2, each Fq2 being 128 characters of canonical
# little-endian Fq written c0 || c1. A value that does not exist is the token
# `none`, so every line kind has a fixed arity.
#
#   fq6_ops  <a> <b> <a+b> <a-b> <a*b> <a^2> <1/a> <a*v> <a^q> <a^(q^2)> <a^(q^3)>
#   fq6_frob <a> <i> <a^(q^i)>     i in 0..6, so every Frobenius table entry is read
#   fq6_pow  <a> <e> <a^e>         e is a plain 256-bit integer, not reduced
#
# Fq6 has no `conjugate`: it is a cubic extension of Fq2 and has no order-two
# automorphism over it. Conjugation lives on Fq12, in fq12_kats.txt.
";

fn fq6_ops_line(out: &mut String, a: &Fq6, b: &Fq6) {
    let mut v = Fq6::ZERO;
    v.c1 = Fq2::ONE;
    let _ = writeln!(
        out,
        "fq6_ops {} {} {} {} {} {} {} {} {} {} {}",
        hex_fq6(a),
        hex_fq6(b),
        hex_fq6(&(*a + *b)),
        hex_fq6(&(*a - *b)),
        hex_fq6(&(*a * *b)),
        hex_fq6(&a.square()),
        opt_fq6(a.inverse()),
        hex_fq6(&(*a * v)),
        hex_fq6(&frobenius6(a, 1)),
        hex_fq6(&frobenius6(a, 2)),
        hex_fq6(&frobenius6(a, 3)),
    );
}

fn frobenius6(a: &Fq6, power: usize) -> Fq6 {
    let mut out = *a;
    out.frobenius_map_in_place(power);
    out
}

fn fq6_kats() -> String {
    let mut out = String::from(FQ6_HEADER);
    let mut rng = Rng::new(FQ6_SEED);
    let edges = fq6_edges();

    out.push_str("\n# --- the edge grid ---\n");
    for a in &edges {
        for b in &edges {
            fq6_ops_line(&mut out, a, b);
        }
    }

    out.push_str("\n# --- random pairs ---\n");
    let mut seen = Vec::new();
    for _ in 0..RANDOM_VECTORS {
        let (a, b) = (next_fq6(&mut rng), next_fq6(&mut rng));
        seen.push(hex_fq6(&a));
        fq6_ops_line(&mut out, &a, &b);
    }
    crate::assert_distinct(&seen, "random Fq6 elements");

    // Random elements first, then the edges. A Frobenius line only exercises a
    // table entry when the coefficient that entry multiplies is nonzero, so the
    // generic elements are the ones that read the table -- and they are what a
    // reader, or the corruption sweep in `tests/kats.rs`, should meet first.
    out.push_str("\n# --- the Frobenius at every power: random elements, then the edges ---\n");
    let mut samples: Vec<Fq6> = (0..FROBENIUS_SAMPLES).map(|_| next_fq6(&mut rng)).collect();
    samples.extend(edges.iter().copied());
    for a in &samples {
        for i in 0..6 {
            let _ = writeln!(
                out,
                "fq6_frob {} {} {}",
                hex_fq6(a),
                i,
                hex_fq6(&frobenius6(a, i))
            );
        }
    }

    out.push_str("\n# --- pow on the edge grid with fixed exponents ---\n");
    for a in &edges {
        for e in FIXED_EXPONENTS {
            let _ = writeln!(
                out,
                "fq6_pow {} {} {}",
                hex_fq6(a),
                hex_exp(&e),
                hex_fq6(&a.pow(e))
            );
        }
    }
    out.push_str("\n# --- pow on random bases and exponents ---\n");
    for _ in 0..40 {
        let a = next_fq6(&mut rng);
        let e = rng.next_exp();
        let _ = writeln!(
            out,
            "fq6_pow {} {} {}",
            hex_fq6(&a),
            hex_exp(&e),
            hex_fq6(&a.pow(e))
        );
    }

    out
}

// ---------------------------------------------------------------------------
// fq12_kats.txt
// ---------------------------------------------------------------------------

const FQ12_HEADER: &str = "\
# fq12_kats v1 -- BN254 Fq12 known-answer tests
# generated by tools/kat-gen against ark-bn254 0.6; do not edit by hand
# regenerate: cargo run -p kat-gen -- tower
# seed: 20260914 (splitmix64)
#
# Fq12 = Fq6[w]/(w^2 - v). One token per value: 768 hex characters written
# c0 || c1, each Fq6 being 384 characters. A value that does not exist is the
# token `none`, so every line kind has a fixed arity.
#
#   fq12_ops  <a> <b> <a+b> <a-b> <a*b> <a^2> <1/a> <conj a> <a^q> <a^(q^2)> <a^(q^3)>
#   fq12_frob <a> <i> <a^(q^i)>   i in 0..12, so every Frobenius table entry is read
#   fq12_pow  <a> <e> <a^e>       e is a plain 256-bit integer, not reduced
#   fq12_final_exp <a> <a^((q^12-1)/r)>
#
# The final exponent is the literal integer (q^12 - 1)/r, 2,790 bits, applied
# by square-and-multiply. It is NOT ark_bn254's own final_exponentiation, which
# returns the Fuentes-Castaneda power f^(m d) with m = 2x(6x^2 + 3x + 1); the
# generator asserts that relationship rather than assuming it.
";

fn frobenius12(a: &Fq12, power: usize) -> Fq12 {
    let mut out = *a;
    out.frobenius_map_in_place(power);
    out
}

fn fq12_ops_line(out: &mut String, a: &Fq12, b: &Fq12) {
    let mut conj = *a;
    conj.conjugate_in_place();
    let _ = writeln!(
        out,
        "fq12_ops {} {} {} {} {} {} {} {} {} {} {}",
        hex_fq12(a),
        hex_fq12(b),
        hex_fq12(&(*a + *b)),
        hex_fq12(&(*a - *b)),
        hex_fq12(&(*a * *b)),
        hex_fq12(&a.square()),
        opt_fq12(a.inverse()),
        hex_fq12(&conj),
        hex_fq12(&frobenius12(a, 1)),
        hex_fq12(&frobenius12(a, 2)),
        hex_fq12(&frobenius12(a, 3)),
    );
}

fn fq12_kats() -> String {
    let mut out = String::from(FQ12_HEADER);
    let mut rng = Rng::new(FQ12_SEED);
    let edges = fq12_edges();

    out.push_str("\n# --- the edge grid ---\n");
    for a in &edges {
        for b in &edges {
            fq12_ops_line(&mut out, a, b);
        }
    }

    out.push_str("\n# --- random pairs ---\n");
    let mut seen = Vec::new();
    for _ in 0..RANDOM_VECTORS {
        let (a, b) = (next_fq12(&mut rng), next_fq12(&mut rng));
        seen.push(hex_fq12(&a));
        fq12_ops_line(&mut out, &a, &b);
    }
    crate::assert_distinct(&seen, "random Fq12 elements");

    // Random elements first; see the note in `fq6_kats`.
    out.push_str("\n# --- the Frobenius at every power: random elements, then the edges ---\n");
    let mut samples: Vec<Fq12> = (0..FROBENIUS_SAMPLES)
        .map(|_| next_fq12(&mut rng))
        .collect();
    samples.extend(edges.iter().copied());
    for a in &samples {
        for i in 0..12 {
            let _ = writeln!(
                out,
                "fq12_frob {} {} {}",
                hex_fq12(a),
                i,
                hex_fq12(&frobenius12(a, i))
            );
        }
    }

    out.push_str("\n# --- pow on the edge grid with fixed exponents ---\n");
    for a in &edges {
        for e in FIXED_EXPONENTS {
            let _ = writeln!(
                out,
                "fq12_pow {} {} {}",
                hex_fq12(a),
                hex_exp(&e),
                hex_fq12(&a.pow(e))
            );
        }
    }
    out.push_str("\n# --- pow on random bases and exponents ---\n");
    for _ in 0..40 {
        let a = next_fq12(&mut rng);
        let e = rng.next_exp();
        let _ = writeln!(
            out,
            "fq12_pow {} {} {}",
            hex_fq12(&a),
            hex_exp(&e),
            hex_fq12(&a.pow(e))
        );
    }

    out.push_str("\n# --- the exact final exponentiation ---\n");
    let exponent = full_final_exponent();
    let m = fuentes_castaneda_multiplier();
    for a in edges
        .iter()
        .filter(|a| !Zero::is_zero(*a))
        .copied()
        .chain((0..FINAL_EXP_SAMPLES).map(|_| next_fq12(&mut rng)))
    {
        let value = a.pow(&exponent);
        // The output has order dividing r, and arkworks' own routine returns
        // the fixed power of it that Must-be-exact 6 forbids. Both checked,
        // so a change in either is caught here and not in a test.
        assert_eq!(
            value.pow(Fr::MODULUS.0),
            Fq12::one(),
            "the final exponentiation lands in the order-r subgroup"
        );
        assert_eq!(
            ark_final_exponentiation(&a),
            value.pow(&m),
            "arkworks' final exponentiation must be the Fuentes-Castaneda power"
        );
        let _ = writeln!(out, "fq12_final_exp {} {}", hex_fq12(&a), hex_fq12(&value));
    }

    out
}

/// `ark_ec`'s BN final exponentiation, reached through the pairing engine.
fn ark_final_exponentiation(f: &Fq12) -> Fq12 {
    <ark_bn254::Config as ark_ec::bn::BnConfig>::final_exponentiation(
        ark_ec::pairing::MillerLoopOutput(*f),
    )
    .expect("a nonzero Fq12 has a final exponentiation")
    .0
}

/// `m = 2x(6x^2 + 3x + 1)`, the fixed multiplier the Fuentes-Castañeda hard
/// part introduces, reduced mod `r` — which is exact on a value whose order
/// divides `r`.
fn fuentes_castaneda_multiplier() -> Vec<u64> {
    let x = BigUint::from(constants::BN_PARAMETER_X);
    let m = 2u32 * &x * (6u32 * &x * &x + 3u32 * &x + 1u32);
    (m % BigUint::from(Fr::MODULUS)).to_u64_digits()
}

// ---------------------------------------------------------------------------

pub fn generate() {
    crate::write_vectors("crates/curve/tests/vectors/fq6_kats.txt", &fq6_kats());
    crate::write_vectors("crates/curve/tests/vectors/fq12_kats.txt", &fq12_kats());
}
